### ISSUE TITLE
Styles: Update select

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1054]
**Design**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7802%3A33963&t=NxYB7ZrwohQXWwaV-0

```[tasklist]
### Tasks
- [ ] Validation states
- [ ] Check floating label behaviour
- [ ] Check margins for hints and validation messages
- [ ] Check paddings
- [ ] https://github.com/swisspost/design-system/issues/3216
- [ ] Design review
```

**Comment by gfellerph** [comment]
Closing in favor of v2 select
