### ISSUE TITLE
Add utilities for the new shadows

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1191]
There are five new elevation levels defined ([Shadows - Figma](https://www.figma.com/file/ojCcgC5Zd12eUSzq6V5m24/Foundations?node-id=170%3A204&t=mpMgV7HITyCixbHW-0)).

Please not that in order to create these shadows, two box-shadows are being layered.

![image](https://user-images.githubusercontent.com/1659006/221611352-364953bb-9dc1-4cf5-923e-ce11c1fcb19a.png)

```[tasklist]
### Tasks
- [ ] Add sass variables with the shadow definitions
- [ ] Add utility classes for all five levels
- [ ] Create a documentation page in storybook for elevation, documenting the new shadows
```
