### ISSUE TITLE
Add new sizing variables

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1195]
Implement the new sizing variables for the styles package.

Design: https://www.figma.com/file/ojCcgC5Zd12eUSzq6V5m24/Foundations?node-id=3%3A4&t=NzPDShQYlcE7HnxN-0
Comments on the change: https://github.com/swisspost/design-system/discussions/588

See also #684 

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/1248
- [ ] Create variables for the new sizes
- [ ] https://github.com/swisspost/design-system/issues/1274
- [ ] Compile a list of components/cases where 1:1 replacement is not possible (breaking changes)
- [ ] https://github.com/swisspost/design-system/issues/1275
- [ ] https://github.com/swisspost/design-system/issues/541
```

**Comment by alizedebray** [comment]
@gfellerph @oliverschuerch 
The decision to go with pixel sizes makes a lot of sense!
However, spacing classes often tend to pile up, so how about keeping it short and dropping the `-size` in class names (i.e. `pe-112` au instead of `pe-size-112` )?

**Comment by oliverschuerch** [comment]
@alizedebray I think this is a good idea. It will only generate one problem:
Bootstrap defines for example the following classes for {property}{sides}-{size}:
`pe-0`, `pe-1`, `pe-2`, `pe-3`, `pe-4`, `pe-5`, `pe-auto`
https://getbootstrap.com/docs/5.3/utilities/spacing/

We should override the bootstrap variable `$spacers` completly, to get rid of the unwanted classes like `pe-3`, `pe-5`, etc.

**Comment by oliverschuerch** [comment]
@alizedebray I would suggest the following formats for the sizing:

| Topic | Format |
| :- | :- |
| SCSS variables | `$size-{size}` |
| CSS variables | `--size-{size}` |
| Margin classes | `.m-{size}` `.m-{breakpoint}-{size}`<br/>`.mt-{size}` `.mt-{breakpoint}-{size}`<br/>`.mb-{size}` `.mb-{breakpoint}-{size}`<br/>`.ms-{size}` `.ms-{breakpoint}-{size}`<br/>`.me-{size}` `.me-{breakpoint}-{size}`<br/>`.mx-{size}` `.mx-{breakpoint}-{size}`<br/>`.my-{size}` `.my-{breakpoint}-{size}` |
| Padding classes | `.p-{size}` `.p-{breakpoint}-{size}`<br/>`.pt-{size}` `.pt-{breakpoint}-{size}`<br/>`.pb-{size}` `.pb-{breakpoint}-{size}`<br/>`.ps-{size}` `.ps-{breakpoint}-{size}`<br/>`.pe-{size}` `.pe-{breakpoint}-{size}`<br/>`.px-{size}` `.px-{breakpoint}-{size}`<br/>`.py-{size}` `.py-{breakpoint}-{size}` |
| Height classes | `.h-{size}` `.h-{breakpoint}-{size}` |
| Line-Height classes | `.lh-{size}` `.lh-{breakpoint}-{size}` |

Tell me if your ok with that ;)

**Comment by alizedebray** [comment]
Sounds great!
I created the `.lh-{...}` classes a while ago because Bootstrap didn't provide line-height classes until version 5. But now that they do, we can remove the "absurd" classes and leave the bootstrap ones indeed.
Do you think it might be useful to also add classes for min-width?

**Comment by oliverschuerch** [comment]
Components where one-to-one replacement is not possible.

| Component | Used sizes |
| :- | :- |
| Carousel | .carousel-indicators bottom: `$size-huge` |
| List-Group | item-padding-y: `$size-small-regular`<br/>.list-group-item padding-x: `$size-small-regular`<br/>.list-group-item-big pading-y: `$size-small-large`<br/>.list-group-item-left-icon pading-left: `$size-small-regular`<br/>.list-group-item-left-icon .list-goup-item-svg margin-right: `$size-small-regular` |
| Language-Chooser (Internet-Header) | #languageParent .dropdown-item padding-y: `$size-small-regular` |
| Type (Portal) | h1/.h1/h2/.h2 margin-bottom: `$size-small-large` |
| Size (Mixin) | bezel-small-regular padding-y: `$size-small-regular`<br/>bezel-bigger-regular padding: `$size-small-large`<br/>bezel-medium padding-y: `$size-small-large` |
| Text (Placholders) | %default-modular-spacer margin-y: `$size-huge`<br/>%text-container ul.bulletpoints li:before width/height: `$size-small-large` |
| Animation | transition-distance-small: `$size-small-regular`, transition-distance-large: `$size-huge` |
| Type | blockquote-padding-left: `$size-small-regular` |
| Accordion | body-padding-top: `$size-small-regular` |
| Alert | padding-y: `$size-small-large`, toast-padding-y: `$size-small-regular` |
| Badge | gap-sm: `$size-small-regular`, check-input-height: `$size-small-large` |
| Button | input-btn-padding-x: `$size-small-large`<br/>input-btn-padding-y-rg: `$size-small-large`<br/>input-btn-padding-y-lg: `$size-small-large`<br/>btn-padding-y-rg: `$size-small-regular`<br/>btn-animatoin-discance-md: `$size-small-regular`<br/>btn-icon-size-md: `$size-small-large`<br/>btn-padding-y-lg: `$size-small-large` |
| Card | spacer-y: `$size-small-large` |
| Forms | input-padding-y-lg: `$size-small-large` |
| Modals | dialog-margin: `size-small-regular` |
| Pagination | padding-y-lg: `$size-small-regular` |
| Spinners | spinner-size: `$size-huge`<br/>spinner-size-xs: `$size-small-regular` |
| Subnavigation | link-padding-xs (x-axis): `$size-small-regular`<br/>link-padding-lg (y-axis): `$size-small-large` |
| Tables | cell-padding-y: `$size-small-regular` |

**Comment by gfellerph** [comment]
@oliverschuerch can we close this issue in favor of tokens?

**Comment by oliverschuerch** [comment]
Out of scope or already implemented through tokens.
