### ISSUE TITLE
Update grid behavior

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1225]
Synchronize the grid implementation with the Design. See the [grid analysis issue](https://github.com/swisspost/design-system-planning/issues/91#issuecomment-1453105652) for details and the history of the discussion.

Design: https://www.figma.com/file/ojCcgC5Zd12eUSzq6V5m24/Foundations?t=S9MdGWrTM9E4Kyob-0

## Gutter width comparison

| Viewport | Design | Implementation<sup>1</sup> |
|:--- |:--- |:--- |
| XXS (<400) | Gutter: 12 <br> Margin: 12 | Gutter: 30 <br> Margin: 12 |
| XS (400-600) | Gutter: 12 <br> Margin: 16 | Gutter: 30 <br> Margin: 16 |
| S (600-800) | Gutter: 16 <br> Margin: 32 | Gutter: 30 <br> Margin: 32 |
| M (800-1024) | Gutter: 16 <br> Margin: 32 | Gutter: 30 <br> Margin: 32 |
| L (1024-1280) | Gutter: 16 <br> Margin: 40 | Gutter: 30 <br> Margin: 40 |
| XL (>1280) | Gutter: 16 <br> Margin: 0 <br> Fixed column width of 84 | Gutter: 30 <br> Margin: 128 <br> Container max width: 1440 |

```[tasklist]
### Tasks
- [x] Make gutter widths responsive and update values
- [x] Update container paddings
- [x] Add and adjust container max-width
- [ ] https://github.com/swisspost/design-system/issues/2096
```

**Comment by gfellerph** [comment]
Discuss with Design again, when going from 1023 to 1024 content shrinks as well. Could we use `vw` padding?

**Comment by oliverschuerch** [comment]
Final adjunstments

 | Element | Property | XS | SM | RG | MD | LG | XL | XXL | 
| :- | :- | :- | :- | :- | :- | :- | :- | :- |
| .container | padding-inline | 12px | 16px | 16px | 32px | 32px | 40px | 120px |
| .container-fluid | padding-inline | 12px | 16px | 16px | 32px | 32px | 32px | 32px |
| .row / .col | gutter | 12px | 16px | 16px | 16px | 16px | 16px | 16px |
