### ISSUE TITLE
Remove deprecated font-size variables

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1301]
With https://github.com/swisspost/design-system/pull/1298/files, the named font-size variables have been deprecated. These variables can be removed with the next major version and the usage across the Design System can be updated to the new variables. This is a breaking change because the new variables cannot be mapped 1:1 due to changes in font-size.

```[tasklist]
### Tasks
- [ ] Remove old variables (https://github.com/swisspost/design-system/pull/1298/files#diff-9d8ca8035b1f5dc4460008e62e276fc78eb8dacfd26ee44a9f5085283e9608deR5)
- [ ] Update usage across the Design System (make sure the old variables are not used anywhere)
- [ ] Update documentation
- [ ] https://github.com/swisspost/design-system/issues/3399
```

**Comment by schaertim** [comment]
Replacing the font-size variables does not make sense at this point because it would have to be reworked with the implantation of the tokens anyway.
