### ISSUE TITLE
Remove deprecated line-height-calc function

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1303]
With https://github.com/swisspost/design-system/pull/1298 the font-size-calc function got deprecated and can be removed for the next major version.

```[tasklist]
### Tasks
- [x] Remove the function (https://github.com/swisspost/design-system/pull/1298/files#diff-e2b80354d4eb5258dcb8a8b3bc7119e54259ff59eda1ac074c0501fe05c16e92R5)
- [ ] Inform about the change in the migration instructions
- [ ] https://github.com/swisspost/design-system/issues/3399
```
