### ISSUE TITLE
Remove deprecated valid and invalid tooltip styles

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1304]
With https://github.com/swisspost/design-system/pull/1298 the invalid and valid tooltip variants of the validation feedback have been deprecated. As they are absolutely positioned variants of the validation feedback messages otherwise used, they can be replaced with feedback messages in most cases.

```[tasklist]
### Tasks
- [x] Remove tooltip variant (https://github.com/swisspost/design-system/pull/1298/files#diff-317441aa6090b5afa02af3a545b7eee5ca344e1d78b8aedb08e397b93553f956R5)
- [x] Update documentation if necessary
- [ ] Write migration instructions
- [ ] https://github.com/swisspost/design-system/issues/3399
```
