### ISSUE TITLE
Remove deprecated line-height variables

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1305]
With https://github.com/swisspost/design-system/pull/1298 the named line-height variables have been deprecated. They can be removed in the next major version.

```[tasklist]
### Tasks
- [x] Remove the variables (https://github.com/swisspost/design-system/pull/1298/files#diff-29ba5feb081f544966b5bad443a8496142bcb81a7ff12645b380b740eab45289R5)
- [x] Update remaining usages within the Design System
- [x] Update the documentation
- [x] Write migration instructions
- [ ] https://github.com/swisspost/design-system/issues/3399
```
