### ISSUE TITLE
Template for sorry pages

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1429]
It would be helpful to have a generic template for error pages like 404 not found, sorry an unexpected error happened etc. that can be integrated with each online service.

**Design**: https://www.figma.com/file/TU39fOLV5ZFGzjC0gKCQa9/Beispiel-Layouts?type=design&node-id=4120%3A101371&t=Y1e0IrZlpLa2Ly6e-1

**Benefits**:
- Error messages can be personalized if they are implemented by each online service (potential to be more helpful)
- We can provide a web component that's easy to implement and provides a consistent look

**Dangers**:
- Error pages will diverge from service to service (style and tonality)

```[tasklist]
### Tasks
- [X] Discuss with Design Team
- [X] Research best practices from other Design Systems
- [ ] Decide on a solution
- [ ] Generic error image needed for other cases (or remove image for other cases)
```

## Examples
- https://places.post.ch/bla
- https://sorry.post.ch
- https://www.post.ch/bla

[![image](https://github.com/swisspost/design-system/assets/1659006/d7135a06-5e71-4cb0-add1-54dbe95a8c32)](https://service.post.ch/notexisting)

**Comment by gfellerph** [comment]
@swisspost/design-system-engineers re-prioritize the issue, I got a request for an ETA.

**Comment by gfellerph** [comment]
- [ ] Create a template without additional CSS, just using CSS utilities
- [ ] Check with Rouven for art direction on wide screens for the image
- [ ] No web components!
