### ISSUE TITLE
Add the radio button card component

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1469]
There is a new component called radio button card. 

![image](https://github.com/swisspost/design-system-planning/assets/1659006/bf711ea4-a18e-4ba6-9751-06b10a6ec1b0)

**Design**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=12335-38389&t=CrkKE9UfOva5tSRZ-0

```[tasklist]
### Tasks
- [x] Implement the radio button card component as CSS component
- [x] Create a story for this component (don't document this in the Demo)
- [x] Add visual regression tests for this component
- [ ] https://github.com/swisspost/design-system/issues/1602
```
