### ISSUE TITLE
Documentation: migrate to Storybook 7

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1524]
The purpose of this ticket is to migrate documentation to Storybook 7: https://storybook.js.org/docs/react/migration-guide
The storybook should then start without error, changes for specific pages/stories will be handled in separate tickets.

**Migration steps:**
- [x] Create a new package `documentation-v7`
- [x] Set up storybook web-components with lit and typescript
- [x] Add a new netlify page
- [x] Create github actions to create PR previews on the new page
- [x] Set up scripts to start development environment
```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/1644
- [ ] https://github.com/swisspost/design-system/issues/1645
```
