### ISSUE TITLE
Component: Dialog

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1536]
Implement styling for the `<dialog>`[^1] element, replacing the [angular modal](https://design-system.post.ch/#/ng-bootstrap-samples/modal).

```[tasklist]
### Tasks
- [ ] Add a story for dialog
- [ ] Add styles of the modal (the ng-bootstrap styles will be deprecated at some point)
- [ ] Add visual regression tests for the new dialog
- [ ] Add the component to the [component tracking board](https://github.com/orgs/swisspost/projects/4)
```

[^1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
