### ISSUE TITLE
Button update Figma

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1571]
As discussed in https://github.com/swisspost/design-system/issues/1566

```[tasklist]
### Tasks
- [x] Add 56px button variant
- [x] Update font sizes of buttons to the 12/14/16/18 progression
- [x] Add secondary animated button variant
- [x] Add icon position option to the right of the text
- [x] Update the naming to primary, secondary and tertiary
```

**Comment by wueestd** [comment]
Hi @imagoiq we adjusted the button font size but also changed the paddings and gaps: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=10576%3A49992&mode=design&t=7oqrnfHBJ8pn1R7p-1

Can you have a look at this and add it to the PR? If you have any questions about it the next few days, please contact @rouvenpost

**Comment by imagoiq** [comment]
@wueestd @rouvenpost I saw the padding changes. We need to discuss it. Size 40 and 56 use respectively 14px and 18px. We don't support those values currently with the spacing (only 4 by 4px so 12, 16, 20, 24…). I don't see either any change in that regard in this proposal https://github.com/swisspost/design-system/discussions/588
