### ISSUE TITLE
Styles: Update button 

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1573]
Update the button according to https://github.com/swisspost/design-system/issues/1566

**Figma**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=13%3A59&mode=design&t=tRmiTRFurMND9yG7-1

```[tasklist]
### Tasks
- [x] Update font size progression to 12/14/16/18
- [x] Change all colors from transparent colors to full-tone colors (background, color, border)
- [x] Update border of secondary buttons to black-60
- [x] Update color of secondary and tertiary buttons to black-80 (default)
- [x] Update color of tertiary buttons to black on hover
- [x] Update inline-padding of tertiary buttons according to design
```

**Comment by imagoiq** [comment]
On hold since: https://github.com/swisspost/design-system/issues/1571#issuecomment-1641942510
