### ISSUE TITLE
New component: badge

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1589]
The badge is a new atomic component that can be used in different contexts (see examples in design).

**Design**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=11038%3A51303&mode=design&t=yTZZ1Z7EwHoVaMXE-1

**Implementation** (not as its own component): https://next.design-system.post.ch/?path=/story/components-badge--default&args=nested:true

Special requirements:
- Background/text color is changeable depending on use case (use CSS custom property for flexibility with a default of error red)

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/2841
- [ ] Create a web component for the badge
- [ ] Create stories for the badge web component
- [ ] Update usage in the chips to use the new component
- [ ] Add visual regression tests
- [ ] Review with the Design team
```

**Comment by gfellerph** [comment]
Closing as done https://design-system.post.ch/?path=/docs/bec68e8b-445e-4760-8bd7-1b9970206d8d--docs
