### ISSUE TITLE
Styles: don't process core.scss and svg-icon-map.scss

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1594]
The styles package contains two sass files that have zero output:
- core.scss
- svg-icon-map.scss

These files currently get processed to CSS on build because they are not prefixed with an underscore. This results in two empty files in the `dist` directory.

**Expected behavior:**
Prefix both files with underscore so they don't get processed as entry modules by sass.

**Special conditions:**
The `svg-icon-map.scss` is being generated by a gulp task, change the output name of that file in the gulpfile and remove the version without underscore.

```[tasklist]
### Tasks
- [ ] Rename `core.scss` to `_core.scss`
- [ ] Rename `svg-icon-map.scss` to `_svg-icon-map.scss` in the gulpfile
- [ ] Remove `svg-icon-map.scss`
- [ ] Create a changeset explaining the change to developers using the Design System ([contribution guidelines for changesets](https://github.com/swisspost/design-system/blob/main/CONTRIBUTING.md#versioning))
```
