### ISSUE TITLE
Styles: Update Stepper

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#1636]
```[tasklist]
### Tasks
- [x] Remove interaction on next step and hover style
- [x] Set badge font-weight to 400 instead of 700
- [x] Set badge font-size to 16px instead of 17px
- [x] Set current active step label to have font-size 16px instead of 17px
- [x] On small viewport, set step label to be under step number (not positionned on the absolute left)
- [x] On small viewport, set step label that are multi-lines to be aligned to the center (except the first and last step)
```
