### ISSUE TITLE
Migrate snapshot test for collapsible

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1678]
```[tasklist]
### Tasks
- [x] blocked by #1647
- [x] copy & paste packages/documentation/cypress/snapshots/components/collapsible.snapshot.ts to packages/documentation-v7/cypress/snapshots/components/collapsible.snapshot.ts
- [x] update url to visit
- [x] create snapshot story
```
