### ISSUE TITLE
Fix checkbox stories

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1770]
```[tasklist]
### Tasks
- [x] Add `checked` property binding to fully sync args between the controls and the story functionality.
- [x] Replace `indeterminate` functionality with a property binding.
- [x] Fix code highlighting in docs.mdx. Switch from css to scss.
- [x] Update `checkbox.stories.tsx` to `checkbox.stories.ts`.
```

https://lit.dev/docs/templates/expressions/#property-expressions

**Comment by b1aserlu** [comment]
As the PR #1928  has overhauled all the scss imports and the rest of the points were already implemented in #1863  this issue has become obsolete
