### ISSUE TITLE
Replace documentation package with documentation-v7

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1801]
```[tasklist]
### Tasks
- [x] Rename the `documentation` package to `documentation-v6`
- [x] Update its package.json accordingly
- [x] Update the `docs` scripts in the root package.json to `docsv6` and update the package name accordingly
- [ ] Add new netlify page `swisspost-design-system-next-v6` to allow preview urls to be created (if needed)
- [ ] Rename and update build.documentation.yaml in the .github/workflows folder accordingly (if needed)
- [ ] Rename and update deploy-documentation.yaml in the .github/workflows folder accordingly (if needed)
- [x] Rename the `documentation-v7` package to `documentation`
- [x] Update its package.json accordingly
- [x] Update the `docsv7` script in the root package.json to `docs` and update the package name accordingly
- [ ] Rename and update build.documentation-v7.yaml in the .github/workflows folder accordingly
- [ ] Rename and update deploy-documentation-v7.yaml in the .github/workflows folder accordingly
- [ ] As far as the old preview urls on `swisspost-design-system-next-v7` are not needed anymore, delete the netlify site with this name
```
