### ISSUE TITLE
Choice cards: Improvements after documentation switch

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1827]
Choice cards were merged unfinished to unblock the documentation migration. There are some tasks to do after the migration.

```[tasklist]
### Tasks
- [ ] Add feature detection for mirroring classes
- [ ] Add a sample script that can be used to track focus changes in firefox (to source?)
- [ ] Check if the 12px size is on the sizing page
- [ ] Add validation controls for the group story
```
