### ISSUE TITLE
Update textarea styles

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1834]
Textareas styling changed. There are now two size variants.

**Design:** https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/branch/MVANE2KzNGq2et3q6T15PC/Components-Post?node-id=7779%3A34916&mode=dev

```[tasklist]
### Tasks
- [x] Update styles for floating label and non-floating label textareas. The floating label has also a small variant now.
- [x] Update the row control in the story: minimum rows allowed are 2 (otherwise it's hard to distinguish between a regular input field).
- [x] Update story, including the sizing section of the docs page.
```

**Comment by gfellerph** [comment]
Breaking change is now in a separate ticket https://github.com/swisspost/design-system/issues/2224

**Comment by davidritter-dotcom** [comment]
Waiting for #1835 to be merged because there would be some conflicts.

**Comment by davidritter-dotcom** [comment]
I encountered some issues with this ticket, that could be discussed:

- The Label of the Input, Select and Textarea should get a smaller font-size in the small variant. I used the `:has` here, or should we just add a class to the label?
- In Figma there are weird paddings like 7px at the top and no padding at the bottom, which gives four different paddings in the small variant.
-  In the select and input, there are totally different paddings and also some strange ones like the top and bottom padding of 17px on the floating select.
