### ISSUE TITLE
Small variants for radio buttons and checkboxes

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1916]
#1861 introduced small variants for radio buttons and checkboxes.

Design for radio buttons: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=14685-71546&mode=dev
Design for checkboxes: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=14685-71361&mode=dev

```[tasklist]
### Tasks
- [x] Refactor checkbox and radio styles and remove the dependency to bootstrap
- [x] Add a small variant for radio buttons and checkboxes
- [x] Document the new variants in storybook
- [x] Update the visual regression tests
```
