### ISSUE TITLE
Create spacing utility documentation

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1936]
```[tasklist]
### Tasks
- [ ] Add a spacing docs page using the [bootstrap docs](https://getbootstrap.com/docs/5.3/utilities/spacing/) and our old [Post-Sizes Reference Table docs](https://design-system.post.ch/#/post-samples/sizing).
- [ ] Add custom made playground to switch between `margin`, `padding`, `gap`, and set the size.
- [ ] Add deprecation warning.
- [ ] Add SCSS import informations.
```

**Comment by oliverschuerch** [comment]
Duplicates: #541
