### ISSUE TITLE
Create sizing utility documentation

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1937]
```[tasklist]
### Tasks
- [ ] Add a sizing docs page using the [bootstrap docs](https://getbootstrap.com/docs/5.3/utilities/sizing/) and our old [Post-Sizes Height & Width docs](https://design-system.post.ch/#/post-samples/sizing).
- [ ] Add custom made playground to switch between `width`, `height` and set the `size`.
- [ ] Add deprecation warning.
- [ ] Add SCSS import informations.
```
