### ISSUE TITLE
Provide translation mechanism for datepicker next/previous button labels

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1954]
According to the datepicker documentation form ngBootstrap: 

> The next/previous button labels can be translated using the standard Angular i18n mechanism. For example, previous month label is extracted under the `ngb.datepicker.previous-month` name. 
https://ng-bootstrap.github.io/#/components/datepicker/overview#i18n

We should provide a solution for projects to be able to implement these labels using the Post standard translation library, @ngx-translate.
```[tasklist]
### Tasks
- [x] Find a solution to translate `ngb.datepicker.previous-month` and `ngb.datepicker.next-month` labels using @ngx-translate
- [x] Document the solution in the demo app
- [ ] If possible, implement this solution in the [blueprint](https://gitit.post.ch/projects/JAVA/repos/blueprint-webapp-js/browse)
```

**Comment by Samoji** [comment]
Any update on this?

The problem is not only related to the datepicker but is more general.
Since we are not using the translation's mechanism of Angular, if we use any third party library that uses angular internationalization ([https://angular.io/guide/i18n-overview](https://angular.io/guide/i18n-overview)) we are not able to translate strings that comes from that library.

Since in the blueprint we are using ngx-translate, I would say that every application coming from the blueprint has this problem.

**Comment by imagoiq** [comment]
It appears that there is no official (or good way) to do it. In 2020, one of the maintainers proposed to work around this with a Directive: https://github.com/ng-bootstrap/ng-bootstrap/issues/2977#issuecomment-658601227. Since 2021, there are no changes or plan to improve the situation.


I implemented an example of this workaround in the following PR. The good part is that it can be easily tested: https://github.com/swisspost/design-system/pull/2315

**Comment by imagoiq** [comment]
@alizedebray What do you think? I'm not sure that we should go this way. Using a directive works, but it also means that the directive needs to be imported everytime the datepicker is used. There is a high chance that people will forget about it.

**Comment by imagoiq** [comment]
We decided to document an example of a directive in the documentation, but not in the blueprint. Unfortunately, there is no way to guarantee that developers will use it. At the moment, our effort will be deployed to progress on web components and provide an alternative way of using ng-bootstrap.
