### ISSUE TITLE
Documentation: Stepper

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1962]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=13414%3A61408&mode=design&t=v21xVVGydMFRQiHB-1
```[tasklist]
### Tasks
- [ ] Component: Horizontal Stepper
- [ ] https://github.com/swisspost/design-system/issues/954
- [ ] https://github.com/swisspost/design-system/issues/3089
- [ ] https://github.com/swisspost/design-system/issues/3090
```

**Comment by wueestd** [comment]
https://design-system.service.gov.uk/patterns/question-pages/#using-progress-indicators

https://design.gs.com/patterns/stepped-progression

https://www.linkedin.com/posts/vitalyfriedman_ux-design-activity-7127577055029796864-0JVK/

**Comment by kaloyanso** [comment]
Hi @Cian77 and @rouvenpost, could you review this component and the documentation when you have the chance and let me know your thoughts :)

**Comment by rouvenpost** [comment]
We should look in to two topic on the Stepped Overview:
1. Accessibility should be improved. The Dark Grey Circle in the Back is difficult to spot. Try to find a better solution.
2. The negative Versions are missing. This Pattern must work on White and Grey Backgrounds.

**Comment by rouvenpost** [comment]
Stepped Progression:
What about the Mobile approach? How does this Pattern work on Mobile? There are no examples and no documentation for Mobile.

**Comment by Cian77** [comment]
Hi @kaloyanso, thanks, great work! I only added my comments.

**Comment by alizedebray** [comment]
@rouvenpost I added some comments directly on Figma

**Comment by rouvenpost** [comment]
I rebuild the Component. Ready for review.
