### ISSUE TITLE
Add the post-portal tech email to the internet-header docs

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1984]
If a new project needs to use the internet-header component, the post-portal team must create a header config in there solution.
To let them know, a project is in the need for such a config, they must be informed by email.
The idea is to add this email and a short description to our internet-header docs.

```[tasklist]
### Tasks
- [x] Ask the post-portal team if it's ok to add the email to our internet-header docs and point out, that this information is public for everyone.
- [ ] Add a short description, which information needs to be sent and add the email address as a mailto link (do this only if the post-portal team agrees).
- [ ] https://github.com/swisspost/design-system/issues/3672
```

**Comment by gfellerph** [comment]
Asked for infos on this one

**Comment by gfellerph** [comment]
**Step 1:**
Integration of header only: contact dm-tec@post.ch directly
Integration of header and KLP: contact KLP first for integration
 
**Step 2:**
Provide these informations to DM Tec:
- ServiceID (ProjektID)
- Languages which you'd like to support
- Allowed referrers per environment (test/int/prod)
- Categories for the Online Service (see https://www.post.ch/de/kundencenter/onlinedienste#t=AllOSTab&sort=%40servicez32xname%20ascending for a list)
- Name of the Online Service in all available languages
- URLs of all environments and languages (links should be dependent on language)
- Abstract in all available languages (will be shown on https://www.post.ch/de/kundencenter/onlinedienste#t=AllOSTab&sort=%40servicez32xname%20ascending)
