### ISSUE TITLE
Remove `regular` breakpoint

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2032]
```[tasklist]
### Tasks
- [ ] #1225
- [ ] Remove `regular` breakpoint from `$grid-breakpoints`
- [ ] Remove `rg` breakpoint from all relevant scss/js maps and docs
- [ ] Adjust `sm` breakpoint to start at a viewport width of `540px`
- [ ] Update Layout documentation (grid, columns, etc.)
```
See "Future Implementation" on https://design-system-grid-visualization.netlify.app/
and https://github.com/swisspost/design-system-planning/issues/91#issuecomment-1746762520

**Comment by gfellerph** [comment]
- [ ] Check with @Cian77 if the Design 2.0 breakpoints line up with the planned changes from this ticket.

**Comment by oliverschuerch** [comment]
After some discussions, we decided to not do this, but instead wait for the next bigger update of the grid system.
