### ISSUE TITLE
Component: Split button

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2126]
Implement the split button web component: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16826%3A34345&mode=design&t=bP9Hi2dc9M5IUf4v-1

![image](https://github.com/swisspost/design-system/assets/1659006/29536905-acae-47d7-b2b3-605e08ff9d91)

**Composition**
This component can be composed based on other components as proposed here: https://www.figma.com/file/Mfy46tN4q3KbDAIbRzfSTj/Popovers-and-dialogs?type=design&node-id=0-1&mode=design&t=PtufcPTL9UIyN9CS-0

In general, it should be easy to use this component, so most of the complexity should be internal.

**External API suggestion**
```html
<post-splitbutton variant="primary" onclick="primaryAction()">
  Primary action text
  <post-menu>
    <post-option onclick="copy()">Copy</post-option>
    <post-option onclick="paste()">Paste</post-option>
  </post-menu>
</post-splitbutton
```
- Two variants are available: primary and secondary
- `<post-menu>` can be used for automatic slot assignment, dropdown and trigger should be handled internally
- default slot could be button content, can also include an icon

```[tasklist]
### Tasks
- [ ] Add a web component named `post-splitbutton`
- [ ] Add a documentation story
- [ ] Add cypress tests
- [ ] Add visual regression tests
- [ ] Test in high contrast mode
- [ ] Design Review
```

**Comment by gfellerph** [comment]
@gfellerph create tickets for the components needed to compose the split button.

**Comment by gfellerph** [comment]
Closing in favor of v2 split button
