### ISSUE TITLE
Adjust Input, Select, Text Area to match figma design

### ISSUE THREAD

**Issue by b1aserlu** [swisspost/design-system#2163]
The Icon was/will be adjusted with the issue #851. PR #2164 

Select:
[https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=3805-22655&mode=design&t=WsfUspZuynideKlR-0](url)

Input:
[https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=8519-34137&mode=design&t=WsfUspZuynideKlR-0](url)

Text Area:
[https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=8948-35969&mode=design&t=WsfUspZuynideKlR-0](url)

```[tasklist]
### Tasks
- [ ] Adjust input-font-sizes
- [ ] Add small/Large version of FormFloating versions of Select, Texarea and Input (where it does not exist already)
- [ ] Adjust the gaps/padding to match figma
```

**Comment by gfellerph** [comment]
Possible duplicates: #1834 and #1835
