### ISSUE TITLE
Create a codepen template for quick prototyping

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2169]
<img width="682" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/eb7ca427-6a35-4c22-a888-1dbd8828a9b6">

https://codepen.io/thevilshadoww/pen/qjVwvZ

Codepen lets us create a template pen that can be used to quickly spin up an environment where the Design System files are loaded from CDN, ready for prototyping or reproducing bugs or exploration...

```[tasklist]
### Tasks
- [ ] Create a codepen template that includes the styles, components and the internet header from CDN
- [ ] Link to that template somewhere in the docs
```

Future improvements that are **not** part of this ticket:
- Each component could have a link to codepen where there's already a pen prepared with that specific component in action

**Comment by imagoiq** [comment]
# Quick feasibility analysis

## UI

We can integrate a new button called "Open in Codepen" next to the "View full-screen" button in the canvas. It can be added through `preview.ts like that:

```
  parameters: {
      docs: {
        canvas: {
          additionalActions: [
            {
              title: 'Open in Codepen',
              onClick: openInCodepen
            }
          ]
        }
     }
   }
```
Note that the title can be a JSX element, and we could include an icon instead.

## 1. Create with a prefilled environment

The onClick event from `additionalActions` can access to private storybook properties with the event parameter. We can access to the latest HTML snippet rendered with `event.view.__STORYBOOK_SERVER_CHANNEL__.data['storybook/docs/snippet-rendered'][0].source`. The array contains only one item. After the page loads for the first time, the array contains the latest canvas rendered on the page. We can check that with the name of the snippet. To get the initial rendered HTML, we should either manually force triggering the current canvas or check if another storybook property contains this information.

Getting CSS and JS for each story is quite hard, so one way to simplify it would be to integrate the CDN version of all resources (components, styles, internet-header, etc.) for each canvas, and only import specific HTML.

Codepen and Jsfiddle both support on the fly creation with a POST API endpoint. Here are the docs: 
* https://blog.codepen.io/documentation/prefill/
* https://docs.jsfiddle.net/api/display-a-fiddle-from-post

Example with jsfiddle (and intellij HTTP client):
```
POST https://jsfiddle.net/api/post/library/pure

{
 "html": "<a>Just a try</a>",
 "css_panel": 1,
 "resources": "https://cdn.jsdelivr.net/npm/@swisspost/design-system-styles/_core.scss"
}
```

### To do

- [ ] Find how to get initial HTML rendered
- [ ] Check other services like CodeSandBox, Glitch or Stackblitz which could be interesting to use to demo Angular components

### Current issues

Most of CodePen is blocked by UHD at the moment. Both CodePen and JSfiddle POST endpoint API are blocked by UHD with the following message: Java from this site is not allowed. Java-Applets or Java-Application from this site is blocked by content policy.

## 2. Display from GitHub Repository

Docs: https://docs.jsfiddle.net/github-integration/untitled-1

With JSfiddle, it's possible to import code from a GitHub repository and create a JSfiddle from it. The disadvantage for us is that we either require to create manually this code or generate it from Storybook. It's also not possible to create dynamically code that matches the arguments in the storybook canvas changed by the user.

**Comment by imagoiq** [comment]
Update about blocking and UHD: UHD unblocked me one page of codepen that I put as an example. The rest of codepen is still blocked.
