### ISSUE TITLE
Styles: Deprecate old Badge, new Badge, Chip

### ISSUE THREAD

**Issue by b1aserlu** [swisspost/design-system#2195]
Umbrella task for the folling Subissues generated from #1864.
## Subissues
```[tasklist]
- [ ] https://github.com/swisspost/design-system/issues/2196
- [ ] https://github.com/swisspost/design-system/issues/2197
- [ ] https://github.com/swisspost/design-system/issues/2198
- [ ] https://github.com/swisspost/design-system/issues/2199
```

**Comment by gfellerph** [comment]
Closing as the umbrella issue is not needed anymore.
