### ISSUE TITLE
Add cypress testing setup for components-angular package

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2215]
We need to be able to test our generated angular components in the same way as our web components.
This needs to be set up in the new package `components-angular`.
```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/2216
- [ ] https://github.com/swisspost/design-system/issues/2217
- [ ] https://github.com/swisspost/design-system/issues/2218
- [ ] https://github.com/swisspost/design-system/issues/2219
- [ ] https://github.com/swisspost/design-system/issues/2220
```

**Comment by gfellerph** [comment]
Depending on #2071

**Comment by gfellerph** [comment]
Closing as won't implement, basic tests are in place.
