### ISSUE TITLE
Zip files before upload

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2228]
![image](https://github.com/swisspost/design-system/assets/1659006/53e145e3-ce94-41cb-a773-39e978248b50)
_https://github.com/swisspost/design-system/actions/runs/6768803990/job/18393940493?pr=2222_

Uploading the built storybook docs and the internet header files takes forever, even if it's only 5MB. Update the upload artifact and download artifact actions to zip or tar the folders before upload and unpack them after download.

```[tasklist]
### Tasks
- [ ] Compress folder before upload in the `actions/artifact-upload` action
- [ ] Unpack files after download in the `actions/artifact-download` action
- [ ] Check if the [official download artifact action from GitHub](https://github.com/actions/download-artifact) can be used over [dawidd6/action-download-artifact](https://github.com/dawidd6/action-download-artifact)
```
