### ISSUE TITLE
Component design: Sidebar

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2236]
<img width="470" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/2db8b2ee-9c25-4f0a-be85-66823140bb6a">

By popular request, we need a design for a sidebar navigation.

```[tasklist]
### Tasks
- [ ] Desktop design
- [ ] Mobile design & behaviour
- [ ] How many levels of link hierarchy are acceptable?
- [ ] How many color variants?
- [ ] Can top level links be clicked or not?
```

**Comment by gfellerph** [comment]
Post Web
<img width="304" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/00479baf-048c-41c5-b3c3-37c90e990de3">
- Links only (expands on page reload)

Post Shop
<img width="321" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/775211b4-99e7-4952-9c05-baf25d01ffb0">
- Links only (expands on page reload)

**Comment by imagoiq** [comment]
## Telman
https://telman.post.ch/

### Desktop
![image](https://github.com/swisspost/design-system/assets/12294151/baa7cb32-11ac-4a42-b546-6cc2ccf7db91)

### Mobile
![image](https://github.com/swisspost/design-system/assets/12294151/7b4afd4c-5c72-42fc-bce8-364241a37ea7)

**Comment by wueestd** [comment]
## Developers Portal



![Image](https://github.com/swisspost/design-system/assets/20660048/d79bc92d-f051-4c17-add3-b12e014a6edb)

https://developer.apis-int.post.ch/ui/apis/05f18c06-2615-4090-b18c-0626151090ae

**Comment by gfellerph** [comment]
duplicate of #2277
