### ISSUE TITLE
Component: Tag

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2237]
A new `tag` component is available in figma. It's a small label, generally appearing inside or in close proximity to another larger interface component, representing a status, property, or some other metadata. It does not provide any interactivity.

**Design**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=11194-50777&mode=design&t=X3G5BXULDm5qk5iX-0
**Component tracker**: https://github.com/orgs/swisspost/projects/4/views/1?pane=issue&itemId=43864320

```[tasklist]
### Tasks
- [x] Add styles for a new component with class name `.tag`
- [x] Add a web component called `post-tag`
- [x] Create a new documentation page for the HTML & CSS tag as well as for the web component tag
- [ ] Add visual regression tests for the tag
```

**Comment by b1aserlu** [comment]
Tag is not yet flaged as ready for developement in figma
