### ISSUE TITLE
Update tooltip styles

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2240]
The Design for tooltips was updated (https://github.com/swisspost/design-system/issues/1510).

Design: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=18199-6387&mode=design&t=X3G5BXULDm5qk5iX-0

```[tasklist]
### Tasks
- [x] Add min height and update padding
- [x] Add variant without arrow (default with arrow)
- [x] Add an arrow control in storybook
- [ ] Target of tooltip must be underlined  if it is an a-Tag with no button and href
```

**Comment by b1aserlu** [comment]
this ticket hast to wait for #2109 to be merged first
