### ISSUE TITLE
Cleanup old and unused branches

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2245]
There are some old and maybe unused branches on our repository which probably could be deleted.
These branches have NOT been merged back into our `main` branch right now, so be careful. And if there is an open PR for one of the listed branches, this means surly that the branch should not be deleted.
The decision which of those branches can be deleted need to be done by the author of each branch.
If you descide that a branch can not be deleted and needs further work, consider merging the `main` branch back to the working branch, so it is at least in a current state.

```[tasklist]
### Tasks
- [ ] [`update-installation-instructions-for-v5`](https://github.com/swisspost/design-system/branches/all?query=update-installation-instructions-for-v5&lastTab=overview) last update june 8th 2023, author @gfellerph
- [ ] [`fix/minReqforDevContainer`](https://github.com/swisspost/design-system/branches/all?query=fix%2FminReqforDevContainer) last update june 15th 2023, author @p45q
- [x] `2023-07-09-update-icons` last update july 9th 2023, author `github-actions[bot]`
- [ ] [`1430-workflow-for-releasing-patch-updates-for-older-versions`](https://github.com/swisspost/design-system/branches/all?query=1430-workflow-for-releasing-patch-updates-for-older-versions) last update august 25th 2023, author @gfellerph
- [ ] [`1503-demo-automate-version-selector`](https://github.com/swisspost/design-system/branches/all?query=1503-demo-automate-version-selector) last update september 7th 2023, author @gfellerph
```

**Comment by imagoiq** [comment]
I'll close this task because it should be done regularly at best (even though it's not a real problem to have many tasks)
