### ISSUE TITLE
[component]: Password input

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#228]
Create a password field component with show/hide password icon button.

**Features:**
- [ ] Name: post-password (?)
- [ ] Input and button are next to each other, input text is never hidden by the button
- [ ] Input element and button text can be passed into a slot, for maximum flexibility with the input element
- [ ] Component state should be updated when slotted input element type changes from the outside

**Options:**
- [ ] Input size: [small, large]
- [ ] Floating label: [yes, no]
- [ ] Password shown/hidden initially

**Methods:**
- [ ] JS API for toggling visibility

**Tests:**
- [ ] Check input type when toggling the visibility

**Design:**
https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=13997-40019&t=FzUdf7TWy8ZadZj7-4
( ↳ as section in page [🔴 Backlog](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=13943-51226) )

**Default:**
```html
<post-password>
  <label slot="label">Label</label>
  <input slot="input" type="password" />
  <span slot="button-text"></span>
</post-password>
```

### Tasks design

```[tasklist]
### 🎨 Design
- [ ] Design component according to WIKIT
- [ ] Update dependencies
- [ ] Add & test compo in layout examples
- [ ] Designer review
- [ ] Documentation: Overview and usage (about, compo overview, compo props, usage, examples)
- [ ] Documentation: Technical documentation (anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

### Tasks development

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] Tokenization
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Password fields in modal: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=20110-20763&mode=design&t=xSsfsncaG7Mwurm6-4

**Comment by oliverschuerch** [comment]
@Vandapanda Why is this in review? The provided link by @gfellerph is not showing a complete state of the password field to me.

**Comment by Vandapanda** [comment]
@oliverschuerch My fault, was told to build it in in the Input component, you can find the link here
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7775%3A33876&mode=design&t=g2Bs8idEX3FzJg3A-1

**Comment by oliverschuerch** [comment]
@Vandapanda There is at least one topic we need to discuss. I've added it to the pattern discussion.

**Comment by gfellerph** [comment]
Link to v2 password field (design required)
