### ISSUE TITLE
Create search field component

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2293]
Create a search field component.

## Design

![image](https://github.com/swisspost/design-system/assets/1659006/c1bfe62c-67d9-477e-86b6-88848ff36f76)

https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16739%3A53259&mode=design&t=i6IlqbsNcGrr8I6l-1

## Features
- Has a placeholder icon that disappears when a search query is entered
- Has a clear button that will clear the current search query and focus the input field afterwards
- Has an optional suggestion list
  - Detailed interaction TBD

### Floating label
```html
<post-search id="search" floating>
  <label for="search">Search</label>
  <post-suggestion-list slot="suggestions">
    <post-suggestion>Se</suggestion>
  </post-suggestion-list>
</post-search>
```

### Non floating label
```html
<label for="search">Search</label>
<post-search id="search">
  <post-suggestion-list slot="suggestions">
    <post-suggestion>Se</suggestion>
  </post-suggestion-list>
</post-search>
```

This approach could use the `<post-popovercontainer>` internally.

```html
<Host>
  <input />
  <post-popovercontainer>
    <slot name="suggestion-list"></slot>
  </post-popovercontainer>
</Host>
```

### Alternative structure proposal (more generic, more complicated):
```html
<post-textinput clearbutton type="search" floating id="search">
  <post-icon name="1000" slot="placeholder-icon"></post-icon>
  <label for="search">Search</label>
</post-textinput>
```

```[tasklist]
### Tasks
- [ ] Reach agreement on component naming and structure
- [ ] Create a web component for the search input
- [ ] Create a documentation page
- [ ] Add end to end tests
```

Initial Design Ticket: https://github.com/swisspost/design-system/issues/1960

**Comment by gfellerph** [comment]
Closing because definition and requirements are outdated. Components that will make a suggestion box possible need to be implemented separately.
