### ISSUE TITLE
Component: Slider

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2297]
Create a new slider component. Sliders allow users to quickly adjust content by dragging actions or using the keyboard to change a single numeric value or a range of values.

## Design
<img width="594" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/1feff38c-d89a-42eb-a613-27a04ff27f50">

https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=18201-21381&mode=design&t=RSmJlLxtSlkSHV3R-0

## Features
- Can have one or two handles to specify a value or a range
- Can have input fields for specifying a precise value
- Can have validation states
- Can have tickmarks (https://github.com/swisspost/design-system/issues/2242), also check the `<datalist>` on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) to see how that's done natively
- Allow thumbs to be dragged across each other (https://ant.design/components/slider, if one thumb is in the middle, the other can be dragged either to the left or right end of the slider)

### Props
- `range`: Indicates if a range can be specified or not (two thumbs)
- `value`: Current value, invalid if it is not representable with the current min/max/step settings
- `min`: Minimum value
- `max`: Maximum value
- `step`: Granularity that value can have

```html
<label for="slider">Slider</label>
<post-slider id="slider" range min="5" max="20" step="5" ></post-slider>
```

```[tasklist]
### Tasks
- [ ] Add a `post-slider` component
- [ ] Add a tab to the slider docs page, documenting the web component
- [ ] Write snapshot tests
- [ ] Review by UX
```

**Comment by imagoiq** [comment]
It could be great to use `<output>` element for displaying the value.

**Comment by gfellerph** [comment]
- [ ] It is possible to use `box-shadow` to imitate the left track side and style it differently (https://stackoverflow.com/questions/72837338/is-it-possible-to-style-input-type-range-with-just-a-left-and-right-color-and-no) in Chrome as well. For the moment, I don't see the need for a web component here.

**Comment by gfellerph** [comment]
Closing in favour of v2
