### ISSUE TITLE
Skiplinks: go to main navigation and search are broken

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2300]
<img width="937" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/035ca8b2-bef4-4650-8718-478cc9707def">

The skiplinks for main navigation and search are not working properly.

```[tasklist]
### Tasks
- [ ] Main navigation: focus should jump to the first main navigation entry.
- [ ] Search: focus should trigger the search button and focus the search input field
- [ ] Improve the e2e tests to catch these issues
```

**Comment by imagoiq** [comment]
@gfellerph please contact the Portal team. They disabled the skiplinks feature of the internet-header and implemented their own, which doesn't use the right ids.

**Comment by gfellerph** [comment]
Opened an issue on portal side: POP-5329. Closing this one as can't fix.
