### ISSUE TITLE
Update support for Angular 17

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2301]
ng-bootstrap released an Angular 17 compatible version (https://ng-bootstrap.github.io/#/getting-started). Therefore, we can update the demo to Angular 17.

```[tasklist]
### Tasks
- [x] Update the demo app to Angular 17
- [x] Update the demo app to ng-bootstrap 16
- [x] Test all ng-bootstrap components manually
- [x] Figure out if this is a major change or not (what kind of changes to the templates were necessary?)
- [x] Update migration instructions on https://design-system.post.ch/#/home
- [ ] Update compatibility table on https://design-system.post.ch/#/home
- [ ] Update compatibility table on https://next.design-system.post.ch/?path=/docs/getting-started-compatibility--docs
- [x] Update peer-dependencies on the styles package (if it's not a breaking change, it's also backwards compatible with 16, a range can be specified with https://stackoverflow.com/questions/66169856/npm-peerdependencies-how-to-specify-major-version-range)
- [ ] Update the common tracing package (bitbucket)
- [ ] Update the blueprint to Angular 17
- [x] Update the intranet-header workspace to Angular 17
- [x] Update the intranet-header workspace to ng-bootstrap 16
```
