### ISSUE TITLE
Basic list: update styles

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2342]
Add a html/css component called "Basic List" with the updated styles.

Design: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=19518-5339&mode=design&t=U46PYhOVAdzniAnK-0

```[tasklist]
### Tasks
- [ ] Add a list component story
- [ ] Discuss what to do with the utility story, as it would be largely a duplicate
- [ ] Add visual regression tests
```

**Comment by imagoiq** [comment]
List is not yet flagged as ready for development in Figma

**Comment by gfellerph** [comment]
Closing as won't do until figma is ready.
