### ISSUE TITLE
Remove grid container helper classes

### ISSUE THREAD

**Issue by b1aserlu** [swisspost/design-system#2399]
Remove the following in #2041 deprecated classes.

```[tasklist]
### Tasks
- [ ] Remove `.vertical-gutters` (use gutter classes instead, e.g. `.g-*`, `.gy-*` or `.gx-*`)
- [ ] Remove `.row.border-gutters`
- [ ] Remove `.container-reset`
- [ ] Remove `.container-reset-left` and `.container-reset-right`
- [ ] Remove `.container-fluid-#{$breakpoint}`
```
