### ISSUE TITLE
Update stylelint and dependencies

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2435]
Stylelint updated to v16 and esm exports only. Plugins need to be updated at the same time.

Merge the open PRs into one.

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/pull/2418
- [ ] https://github.com/swisspost/design-system/pull/2431
- [ ] https://github.com/swisspost/design-system/pull/2434
- [ ] https://github.com/swisspost/design-system/pull/2419
- [x] Add a renovate rule to group stylelint major updates (like Angular)
- [ ] https://github.com/swisspost/design-system/issues/3121
```
