### ISSUE TITLE
Publish the Demo App to a new netlify site used as archive

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2469]
Create a new netlify site that serves as an archive for the Demo App.

In order to migrate from the Demo App to Storybook, we need the Angular documentation still available for reference, since documentation pages in Storybook will need somewhere to point to.

Creating a new site will have the benefit of a stable URL while maintaining the possibility to publish updates in cases of emergency.

```[tasklist]
### Tasks
- [ ] Create a new netlify site
- [ ] Add site name to GitHub secrets
- [ ] Update the release demo app action to publish to the new site as well (don't remove the current publish step yet, just duplicate it)
```

**Comment by imagoiq** [comment]
Instead of creating another site, I think it's easier to just add an alias in Netlify and when we'll do the switch with next, we can just set this alias as the primary domain, remove "design-system.ch" and assign it to next.design-system site.
