### ISSUE TITLE
Migration: Document post cards

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2480]
Document the Product Card component (https://design-system.post.ch/#/post-samples/card) in storybook. 

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/2469
- [ ] Migrate product card documentation
- [ ] https://github.com/swisspost/design-system/issues/2567
```
