### ISSUE TITLE
Migration: Document stepper

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2481]
Document the `ng-bootstrap` stepper component (https://design-system.post.ch/#/post-samples/stepper) in storybook. 

Since this is an Angular component, it can't be displayed in storybook. Use the Intranet Header documentation as a reference https://next.design-system.post.ch/?path=/docs/components-intranet-header-getting-started--docs for how to document with code only and link to the Demo App archive for a live demo.

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/2469
- [ ] Migrate stepper documentation
```

**Comment by oliverschuerch** [comment]
Add Content to the new docs page:
- [ ] Name
- [ ] Link to ng-bootstrap docs
- [ ] Link to archived demo docs
- [ ] Installation guide (css imports)
- [ ] Post specific informations/examples
