### ISSUE TITLE
🪿 Migrate storybook to design-system.post.ch

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2483]
After the content migration (most of the tasks in https://github.com/swisspost/design-system/milestone/10), the storybook docs can be published to the main documentation address.

```[tasklist]
### Tasks
- [x] Migrate all `ng-bootstrap` content (2470 - 2480)
- [ ] https://github.com/swisspost/design-system/issues/2486
- [ ] https://github.com/swisspost/design-system/issues/2485
- [x] Check all links that go https://next.design-system.post.ch and change them to point to https://design-system.post.ch
- [x] Publish the demo to the demo archive netlify site only instead of the main one
- [x] Publish storybook to the main site instead of next (keep next as is, will be used later)
- [x] Add an entry to the versions.json that allows switching to the archived demo app
- [x] Check external links like on the wiki, in Figma, Teams and other sources that point to next and change them to the current docs
- [x] General accessibility checks
- [x] Remove the beta alert
- [x] Add back links to old documentation for ngb components
```
