### ISSUE TITLE
Set up emergency publish workflow

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2484]
It might be necessary to still do some releases on the archived documentation to update links or deprecation warnings. Therefore it would be good if the workflow for publishing could be adapted to a release branch.

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/2483
- [x] Create a `release/angular-demo-archive` branch
- [ ] Update the demo release workflow so it publishes to the archive on this branch
```
