### ISSUE TITLE
Styles: update checkbox style

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2525]
**Design**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&mode=design&t=jKS2ePOhRahQETtC-0

**Focus style**: Since the focus now spans the label as well, we need to use the `:focus-within` https://caniuse.com/?search=focus-within pseudo class to set the focus on the wrapping `div`.

If it isn't already done, create a mixin (not a placeholder (it's less error prone and more flexible)) for the focus style as all the components will share this style in the future.

```[tasklist]
### Tasks
- [x] Update focus style
- [x] Update disabled styles
- [ ] https://github.com/swisspost/design-system/issues/2681
```
