### ISSUE TITLE
Styles: Update text input

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2527]
**Design**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7775%3A33876&mode=design&t=VnF7Nfba4zszs6Kt-1

**Floating label animation**: An empty floating label text input shows the placeholder text, if it is specified. This placeholder appears as soon as the label begins to float to the top. As the label is above the placeholder, it covers the placeholder during the floating to the top. This creates a visually unpleasing effect and looks broken. I think the effect can be reduced by animating the opacity on the placeholder with the same duration as the label floating animation (implement and verify with Design).

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/1835
- [x] Update focus styles
- [x] Update valid state styles
- [x] Update disabled styles
- [x] Improve floating label animation
- [ ] Design review
- [x] Update hover state
```

**Comment by imagoiq** [comment]
About the floating variant with small size, there is the following ticket + a PR: https://github.com/swisspost/design-system/issues/1835
https://github.com/swisspost/design-system/pull/2396

**Comment by davidritter-dotcom** [comment]
Waiting for #2857 to be merged.

**Comment by davidritter-dotcom** [comment]
- focus style gets fixed with #3166
- icon gets added to the validation-feedback message with  #2978
