### ISSUE TITLE
Add heading-level property on post-accordion

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2576]
Currently, we can specify `heading-level` property on `post-accordion-item` (it's not referenced in the documentation). It would be good to be able to define it on the whole `post-accordion` element.

```[tasklist]
### Tasks
- [ ] Add heading-level property on post-accordion
- [ ] Document heading-level property on `post-accordion` on the accordion page
- [ ] Make the heading level property required
```

**Comment by imagoiq** [comment]
Depends on https://github.com/swisspost/design-system/issues/2571

**Comment by gfellerph** [comment]
Discussion: release a tiny major change, make the prop required
