### ISSUE TITLE
Popover: update styles

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2622]
Update popover styles according to the design.

**Design**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=18199%3A9441&mode=design&t=SLPwF9JvctxA2O4s-1

```[tasklist]
### Tasks
- [x] Close button dimensions
- [x] Close button colors and states will be updated with button style updates
- [x] Padding right
- [x] Size of the little pointer arrow (popovercontainer)
```
