### ISSUE TITLE
Remove Input Group and utilities/common page before migration to new documentation

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2652]
Need to be triage with the following question: should we remove the page before publishing the new docs and adding it again, but completed after? Or should we complete it before the end of February?

The page is empty:
https://next.design-system.post.ch/?path=/docs/components-forms-input-group--docs

```[tasklist]
### Tasks
- [x] Remove Utilities/Common page
- [x] Remove input group page
- [x] Create tickets for styling input group and document it
- [x] Create a ticket for utilities common docs page
```
