### ISSUE TITLE
Footer: small variant

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2656]
There is a small variant of the footer available.

**Design**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=185%3A260&mode=design&t=mGeQ7btbwNVae33N-1

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/1586
- [ ] Implement the small variant of the footer as an option on `<swisspost-internet-footer>`
- [ ] Document in storybook
- [ ] Design review
- [ ] Test in high contrast mode
```

**Comment by gfellerph** [comment]
Will be implemented with footer 2.0
