### ISSUE TITLE
A11y – Check color-contrast on post-alert with success background

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2683]
Reported by cypress-axe: 
![Cypress_AgCBu2jsPq](https://github.com/swisspost/design-system/assets/12294151/3c597353-8b4d-457d-a269-38cd14fdc06e)

```[tasklist]
### Tasks
- [ ] Fix issues with color contrast
- [ ] Enable 'color-contrast' rules again (by removing the option) on the e2e test
- [ ] Update success color
```

**Comment by gfellerph** [comment]
@imagoiq please check the current state of the alert, which success color is actually used

**Comment by imagoiq** [comment]
So @alizedebray was totally right, the background-color was changed with [PR adding c](https://github.com/swisspost/design-system/pull/2634/files#diff-ea39372332f789359d4399dfcaab53517466cc5b2bed3ce4f7891d272b3a418b)
Text color was automatically adapted with the algorithm.

**Comment by oliverschuerch** [comment]
Wait until #2784 is done and check again!
