### ISSUE TITLE
Add new white/black alpha colors

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2716]
https://www.figma.com/file/ojCcgC5Zd12eUSzq6V5m24/Foundations-Post?type=design&node-id=26-111&mode=design&t=89C4WHH0EIozKIWj-0

```[tasklist]
### Tasks
- [x] Update brand colors
- [x] Fix signal colors
- [x] Add new colors
- [x] Fix TODO for radio and checkbox in https://github.com/swisspost/design-system/pull/2813/files
```

**Comment by imagoiq** [comment]
Changed priority to urgent as some components require those new colors.
