### ISSUE TITLE
Update slider styles

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2765]
There is a way to style the left part of the track in every browser and the focus styles changed. Update the slider CSS component accordingly.

**Design**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16545%3A53351&mode=design&t=fYGLSZ9g8fLp5RDs-1

```[tasklist]
### Tasks
- [ ] Update the styles for left track according to https://stackoverflow.com/questions/72837338/is-it-possible-to-style-input-type-range-with-just-a-left-and-right-color-and-no
- [x] Rename the "Range" page on the docs to "Slider"
- [ ] Update focused styles
- [ ] Design review
```

**Comment by imagoiq** [comment]
After discussion on https://github.com/swisspost/design-system/pull/2781 in the Pattern discussion today, we'll go with option 4 and have the focus style on the whole group of input and label and use the css workaround with box-shadow.
