### ISSUE TITLE
Update internet-header breadcrumb web-component

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2798]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=154-0&mode=design&t=KcGXo3HbBpJRhkuC-0

```[tasklist]
### Tasks
- [ ] Check and/or update basic styles
- [ ] Add responsive sizing behaviour (mobile/desktop)
- [ ] Check if we need to change the flex behaviour on small screens to get around the error showed in the image below
- [ ] Update docs
```
![Breadcrumb on Mobile with Breadcrumb Buttons](https://github.com/swisspost/design-system/assets/9716662/62d32f1c-328e-450f-9b64-4aa0f9e7bcf7)

**Comment by gfellerph** [comment]
@oliverschuerch check with @rouvenpost how the breadcrumb items should collapse and if the buttons can wrap to a new line.

**Comment by oliverschuerch** [comment]
Decition:

- Collapse on all device sizes if space is insufficent. Collapse all but last or none.
- Wrap help- and contact-buttons to next line (align them to the right) if space for breadcrumb is insufficent.

**Comment by gfellerph** [comment]
Closing in favor of #3277 (new implementation)
