### ISSUE TITLE
Components: Add a pagination web-component

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2801]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16523-53293&mode=design&t=KcGXo3HbBpJRhkuC-0

```[tasklist]
### Tasks
- [ ] Create Web-Component
- [ ] Create e2e tests
- [ ] Create snapshot tests
- [ ] Export component in `components/src/index.ts`
- [ ] Add basic implementation of component in `componts-angular/projects/consumer-app`
- [ ] Create component docs
```

**Comment by gfellerph** [comment]
@gfellerph add a ticket for a basic component

**Comment by gfellerph** [comment]
Closing in favour of v2
