### ISSUE TITLE
Add styles and HTML/CSS stories for the badge component

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2841]
Design:
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=11038%3A51303&mode=dev

```[tasklist]
### Tasks
- [ ] Update the badge styles
- [ ] Update the badge documentation
- [ ] Update the badge visual regression tests
- [ ] Create migrations for the nested badges to badge
```
