### ISSUE TITLE
Chore the generated preview URLs

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2849]
Preview URLs generated on newly opened PRs are still pointing to the Demo App and/or the next (Storybook) documentation.

```[tasklist]
### Tasks
- [x] Check if we still need to build/release the old Demo App.
- [ ] If we still need it, let the URL for the Demo app be generated with the `archive` keyword (e.g. https://preview-{PR-ID}--swisspost-design-system-archive.netlify.app).
- [ ] Remove the generated URL for the Storybook docs, so there is no `next` keyword in it anymore (https://preview-{PR-ID}--swisspost-design-system.netlify.app).
- [ ] Mark up the links in markdown to define a nice text
```
