### ISSUE TITLE
Update focus-ring mixin

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2862]
```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/pull/2861
- [ ] https://github.com/swisspost/design-system/pull/2855
- [x] Use new color variables (which will be implemented with #2861) in focus-ring mixin.
- [x] Check and implement HCM also
- [x] Check for and update components, which do not use the mixin right now.
```

**Comment by oliverschuerch** [comment]
Wait for DEV until #2855 is done.
