### ISSUE TITLE
Add migration guide from v6 to v7

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2864]
```[tasklist]
### Tasks
- [ ] Show how to update angular
- [ ] Explain how to run automigration
- [ ] Show migration path for all breaking changes
```
