### ISSUE TITLE
Switch hydrated selector from `class` to `attribute` in stencil config

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2884]
```[tasklist]
### Tasks
- [x] Update stencil.config.js, see [stencil docs](https://stenciljs.com/docs/config#hydratedflag)
- [x] Fix e2e tests depending on the hydrated class
- [x] Remove hydrated class from story files (for example in tooltip.stories.ts)
- [x] Update e2e tests, especially snapshot tests
```
