### ISSUE TITLE
[component]: Avatar with Name

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2885]
Create a component for user avatars.

![image](https://github.com/swisspost/design-system/assets/1659006/cca64a20-eecb-4a72-bb85-b0f15837aae2)

**Design**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=17162%3A7287&mode=design&t=Q7MUVh3G2mYSJ7OV-1

### Props
- name
- company name (optional)

### Slots
- bubble: slot for the `<post-profile-picture>` component (#3210)

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/2596
- [ ] https://github.com/swisspost/design-system/issues/3210
- [x] Implement the new component `post-avatar`
- [x] Create a documentation page
- [x] Add cypress tests
- [x] Add visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Wait for the Design for the new Header

**Comment by gfellerph** [comment]
Proposing to close this ticket because a dedicated component is not necessary to create this layout.

**Comment by gfellerph** [comment]
Closing as won't do
