### ISSUE TITLE
Form elements – Hover and focus style consistency (w or w/o HCM)

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2893]
```[tasklist]
### Tasks
- [ ] Check how input focus/focus-visible behavior in all browsers
- [ ] Rethink where the outline should be visible (only input, w or w/o validation, what about input with validation where the outline is visible on top of it, input without wrapper like form-range)
- [ ] [Hover style for form-range? What about other component ?](https://github.com/swisspost/design-system/issues/2891)
- [ ] How to style for card-control (which contains an embedded input)?
- [ ] SelectedItem vs Highlight color in High contrast mode. How to style in HCM ?
- [ ] Rethink the mixin?
```
