### ISSUE TITLE
Update documentation design

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2916]
> @rouvenpost  Difficult to differentiate patterns and info around it -> switch to monospace font for docs, frutiger for patterns. Info messages (default, warning), new proposal, also for tabs. Make the icons black and optimize the background.
> 
> 
> 
> Proposal https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=28527-13263&mode=design&t=iwnbvkTdx6cuAysL-0

 _Originally posted by @gfellerph in [#2896](https://github.com/swisspost/design-system/issues/2896#issuecomment-2044895200)_

Update the design of the storybook docs for the following components so it's easier to differentiate between the actual Design System output and the docs for them.

```[tasklist]
### Tasks
- [x] Use monospace font for the docs but keep using Frutiger for the preview
- [x] Restyle alerts outside of the preview according to the proposal
- [x] Restyle tabs outside of the preview according to the proposal
- [ ] Color the icons black
- [ ] Check if #fc0 can be used as background for the navigation
- [ ] Design review
```

**Comment by gfellerph** [comment]
Closing as won't do (maybe a complete overhaul at some point would be nice).
