### ISSUE TITLE
AG Grid POC

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2949]
> @gfellerph Resolution: create a ticket to get more insights on AG grid for figma and dev 

 _Originally posted by @gfellerph in [#2898](https://github.com/swisspost/design-system/issues/2898#issuecomment-2045065356)_

Create a POC with AG Grid community (https://ag-grid.com/javascript-data-grid/getting-started/). Especially have a look at customization (https://ag-grid.com/javascript-data-grid/getting-started/#customising-a-theme).

Also, check other Design Systems for hints on integration
- https://design.baloise.dev/?path=/docs/components-data-display-table--documentation

```[tasklist]
### Tasks
- [ ] Add a docs page for AG Grid and put a demo grid on there
- [ ] Check with @swisspost/design-system-designers on how much we can do in terms of theming
- [ ] Use controls inside the table
- [ ] Customize the markup for cells (e.g. put a button in there)
- [ ] Use custom markup for filters (can we use our components for filtering?)
- [ ] Align with the results of the 2022 survey on datatables, does the community edition provide all the features we need?
```

**Comment by leagrdv** [comment]
PR for the POC is here: https://github.com/swisspost/design-system/pull/5192

Closing this ticket as the POC is done and we decide to move forward with using AG Grid

**Comment by MonsieurBon** [comment]
I don't really understand... Why was this issue closed when the PR was not actually merged? Is there a follow up issue?
