### ISSUE TITLE
Update to node 20

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2955]
Update all GitHub Actions and the engine field in the home package.json to node 20 and advise all devs to do the same.

```[tasklist]
### Tasks
- [x] Update engines setting to v20
- [x] Update lockfile
- [x] Update gitub actions to use node 20
- [x] Update @types/node deps
- [ ] Ensure that codespaces still work
```
