### ISSUE TITLE
Update to pnpm 9

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2956]
pnpm has a new major version (https://github.com/pnpm/pnpm/releases).

```[tasklist]
### Tasks
- [x] Update engines setting to v9
- [x] Update lockfile to v9
- [x] Update github actions to use pnpm 9
- [x] Ensure that codespaces still work
```
