### ISSUE TITLE
Would be nice to have an active state on the current browsed version in the version switch as well. Or at least showing the current browsed version in the version switch toggle.

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2973]
Would be nice to have an active state on the current browsed version in the version switch as well. Or at least showing the current browsed version in the version switch toggle.
![image](https://github.com/swisspost/design-system/assets/9716662/cf7c3ab6-8a80-410c-a839-2057978451cf)

_Originally posted by @oliverschuerch in https://github.com/swisspost/design-system/pull/2970#pullrequestreview-2006167010_
            
```[tasklist]
### Tasks
- [ ] Depends on the v6 release workflow
- [ ] Update toggle button text to the correct version
- [ ] Set active state in the dropdown
- [ ] Update v6 docs
- [ ] Update v7 docs
```
