### ISSUE TITLE
Multi List

### ISSUE THREAD

**Issue by rouvenpost** [swisspost/design-system#2988]
# Description

Implement several list components

## Design

https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=30030%3A39506&mode=design&t=CHPkG8v6O7NVLqsK-1

```[tasklist]
## Tasks
- [ ] https://github.com/swisspost/design-system/issues/3547
- [ ] https://github.com/swisspost/design-system/issues/3548
- [ ] https://github.com/swisspost/design-system/issues/3549
- [ ] https://github.com/swisspost/design-system/issues/3550
```

**Comment by oliverschuerch** [comment]
In my opinion, this should be the same component as the "Link List" [#2979](https://github.com/swisspost/design-system/issues/2979). Therefore it should be a subtype of the Link List, not a own component.
The only differences are:
- There is no arrow icon on the right of the list-item.
- There is a document icon on the left of the list-item.
- The different behaviour of the link (download the file when clicking on it, instead of following the url) can be done in code, by adding the attribute `download`.

Everything else, like adding the file size, must be implemented as content from the consuming project.

**Comment by rouvenpost** [comment]
@oliverschuerch should we merge all the List Types together? Linklist, Documentlist, Action List and Switchlist? Or do we only merge Linklist & Documentlist?

**Comment by rouvenpost** [comment]
I merged all Lists in to one component:
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=30030%3A39506&mode=design&t=CHPkG8v6O7NVLqsK-1

**Comment by oliverschuerch** [comment]
Listen to me: We will not do anything with this task, because there are more specific issues for all the lists listed in the list above. **listseption**
