### ISSUE TITLE
Update the icons package docs

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3010]
```[tasklist]
### Tasks
- [ ] On the page `Serve the icons within your application` update the sections `Angular wrapper package` and `Declare manually Web components` to point out, this are two different ways how to add components to your angular app.
- [ ] Move the section `Serve the icons within your application` from the page `Getting Started/Angular` to the page `Getting Started/Packages/Icons` and merge it with the section `Copy & paste the icons with a postinstall script`.
- [ ] Update the title of the merged section to something like `Selfhosting the icons`.
- [ ] Point out, the difference between a vanillaJS setup (which will need the postinstall script) and the angular way to serve the icons.
- [ ] Point out, that the copied `/assets/post-icons` folder needs to be served by a dev server and be available in the dist folder, to be accessible from the int/prod server.
- [ ] Remove the section `Serve the icons wihin an Angular application` above.
```

**Comment by gfellerph** [comment]
@oliverschuerch we were not sure what to discuss about for this ticket, so we skipped it.

**Comment by oliverschuerch** [comment]
Not relevant anymore
