### ISSUE TITLE
SECURITY.md is out of date

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3011]
```[tasklist]
### Tasks
- [x] Add missing packages
- [x] Update current versions
- [x] Update Supported dates
- [x] Update Supported dependencies
```
