### ISSUE TITLE
Implement resolve aliases in storybook

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3013]
To make imports (of let's say local utils, etc.) simpler, we can add compilerOptions in the tsconfig.json file.
 This will enable us to do this: `import { myUtil } form '@utils/my-util';` instead of this: `import { myUtil } form '../../../../utils/my-util';`.
 
```[tasklist]
### Tasks
- [ ] Add [resolve.alias](https://vitejs.dev/config/shared-options#resolve-alias) to the vite.config.js file
- [ ] Add path aliases to tsconfig.json where usefull
- [ ] Update file imports
```

**Comment by gfellerph** [comment]
Closing as duplicate of #2881
