### ISSUE TITLE
Fix lint configs in projects

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3015]
```[tasklist]
### Tasks
- [ ] Where present, remove `stencil.config.ts` out of the `.eslintignore` file
- [ ] Where present, add `./stencli.config.ts` to the `include` array in the `tsconfig.eslint.json` file
- [ ] Where present, add all generated folders to the `ignores` array in the `.eslintrc.js` file
