### ISSUE TITLE
Add linting for all packages

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3037]
```[tasklist]
### Tasks
- [ ] Add linting config and package.json script for package documentation
- [x] Add linting config and package.json script for package icons
- [x] Add linting config and package.json script for package migrations
```
