### ISSUE TITLE
Add validated focus and hover states to design files

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3043]
In the pattern discussion from the 02.05.2024 we discussed #2972 where we decided to show the focus border on validated (valid or invalid) elements. It would be good if these styles are defined in Figma so it's clear what border color takes precedence.

```[tasklist]
### Tasks
- [ ] Define variant for validated and focused elements
- [ ] Define variant for validated and hovered elements
- [ ] Define variant for validated and disabled elements
```

**Comment by gfellerph** [comment]
Closing as obsolete
