### ISSUE TITLE
Fix dependency to components package in components-angular package

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3113]
The components package is used as a devDependency in the components-angular package.
But since we're doing it like that, the definition of the components package is not ending up in the built/released components-angular [package](https://www.npmjs.com/package/@swisspost/design-system-components-angular?activeTab=code) anymore (visit package.json). Which leads to the fact, that projects need to install it as a direct dependency, only to make the components-angular package work.

While stenciljs [docs](https://stenciljs.com/docs/angular#creating-an-angular-component-library) tells us to install it as a peerDependency, this is not working inside the design-system repo, because we do not install peerDependencies automatically do to the `.npmrc` option `legacy-peer-deps=true`.
The solution for this scenario, would probably be to install the components package inside the components-angular/projects/components/package.json as a peerDependency and install it as well in the angular-workspace itself (/packages/components-angular/package.json).

```[tasklist]
### Tasks
- [x] Install @swisspost/design-system-components as a peerDependency in components-angular/projects/components/package.json.
- [x] Install @swisspost/design-system-components as a direct dependency in components-angular/package.json.
- [x] Test if the consumer app works.
- [x] Test if a project works with only installing the package @swisspost/design-system-components-angular.
```
