### ISSUE TITLE
Fix post-card-control FORM bindings in angular environment

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3115]
The component works fine when used with `formControlName`.

```[tasklist]
### Tasks
- [ ] Test and fix `formControl` binding
- [ ] Test and fix `model` binding
- [ ] Make sure `formControlName` binding still works afterwards
```

**Comment by oliverschuerch** [comment]
Since this is no issue for the projects using the component (there are not a lot), and this component needs to be refactored for v9 anyway, I would suggest to close this ticket.
@gfellerph what do you think?

**Comment by gfellerph** [comment]
Closing as won't do unless it becomse an issue for someone.
