### ISSUE TITLE
Create tokens package

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3146]
Use https://github.com/oliverschuerch/tokens-poc as a base.

```[tasklist]
### Tasks
- [x] Setup package (private: true)
- [x] Update readme.md
- [x] Update contributing.md
- [x] Define where pushed token json files will stay
- [x] Add dependencies with `style-dictionary` and `@tokens-studio/ds-transforms`
- [x] Add package.json scripts
- [x] Add build.js script
- [x] Follow this docs to setup github sync: https://docs.tokens.studio/sync/github
```
