### ISSUE TITLE
Fix used lifecycle hook for initial component property checks

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3153]
`post-icon` and other components throw an error, even when a required property is set.
![image](https://github.com/swisspost/design-system/assets/9716662/c0aedaaa-d1f8-4b89-8aad-6dae9f965da5)

```[tasklist]
### Tasks
- [ ] Call all property `checkNonEmpty` check in `componentDidLoad` hook instead of `componentWillLoad`.
- [ ] Test if the error is gone.
- [ ] https://github.com/swisspost/design-system/issues/3687
```

We can see the same error also in our documentation e2e tests:
![Image](https://github.com/user-attachments/assets/226ac148-edee-46c3-b28f-c9423ef4b224)

Use these to test if the fix works.
