### ISSUE TITLE
Component: Progressbar

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3157]
Create a progressbar component.

### Design
https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=28771-188748&t=hZPnuA7YgRMcKv1M-4
Style meter and progress only, text will be added with the file upload or in specific situations (#1587).

### Implementation
Styling the native `<meter>` and `<progress>` seems to be easier today (https://alessiopuppi.blog/2024/05/03/meter-element/ and https://css-tricks.com/html5-progress-element/) than it was a couple of years ago (https://css-tricks.com/css3-progress-bars/).

#### Progress
The `<progress>` [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element displays an indicator showing the completion progress of a task, typically displayed as a progress bar. [^1]

#### Meter
The `<meter>` [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents either a scalar value within a known range or a fractional value. [^2]

```[tasklist]
### Tasks
- [ ] Create a HTML/CSS component using `<meter>` and `<progress>` as variants based on use case
- [ ] Add a documentation story
- [ ] Add visual regression tests
- [ ] Design review
```
[^1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress
[^2]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter

**Comment by gfellerph** [comment]
Closing in favour of v2
