### ISSUE TITLE
Update to Angular 18

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3184]
```[tasklist]
### Tasks
- [x] Update Angular to 18
- [x] Update typescript
- [x] Update ng-bootstrap
- [x] Check the demo app for bugs
- [x] Add a major changeset
- [x] Create a migration page entry
- [x] Update security.md
- [x] Update peer dependency in styles package
- [ ] Update common-tracing
- [ ] Update ngx-highlight
- [ ] Update ngx-toastr
- [ ] https://github.com/swisspost/design-system/issues/3260
```

**Comment by MonsieurBon** [comment]
Maybe also consider making the components standalone.

**Comment by gfellerph** [comment]
> Maybe also consider making the components standalone.

@MonsieurBon that would be up to ng-bootstrap, we're just providing styles. But the library does not seem to be maintained as actively anymore.
