### ISSUE TITLE
[component]: Breadcrumb

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3207]
Migrate the [breadcrumb list component](https://github.com/swisspost/design-system/blob/main/packages/internet-header/src/components/post-internet-breadcrumbs/components/breadcrumb-list.component.tsx) to the `packages/components` package.

### Proposed markup structure
```html
<post-breadcrumb home-url="/" home-text="Go home">
  <post-breadcrumb-item href="/">Link 1</post-breadcrumb-item>
  <post-breadcrumb-item>Current</post-breadcrumb-item>
</post-breadcrumb>
```

Alternative markup structure to make it easier to put items in the dropdown and mark the last breadcrumb item:
```html
<post-breadcrumb>
    <post-breadcrumb-item></post-breadcrumb-item>
    <post-breadcrumb-item></post-breadcrumb-item>
    <post-breadcrumb-item></post-breadcrumb-item>
    <post-breadcrumb-item></post-breadcrumb-item>
    <post-breadcrumb-current></post-breadcrumb-current>
</post-breadcrumb>
```

### Props
- homeURL: A valid URL to use on the home icon
- homeText: Accessible name for the home icon

### Default slot
Only allowed children are `<post-breadcrumb-item>` elements.

### Notes
- Renders a hidden section with the full length of items to check if there is enough space for all items before rendering the real items. If there is not enough space, ellipsis with a dropdown should render that lists all breadcrumb items but the last. If the last breadcrumb item does not have enough space to fully render, it should end in ellipsis. It should never overflow nor flow on two lines.

```[tasklist]
### 💻 Tasks
- [ ] https://github.com/swisspost/design-system/issues/3277
- [ ] https://github.com/swisspost/design-system/issues/1242
- [x] Web component implementation
- [x] Documentation in Storybook
- [x] Visual regression tests
- [ ] Design review
```
