### ISSUE TITLE
Update workflows to enable previous major version releases

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3217]
```[tasklist]
### Tasks
- [x] Update all github action calls, so they run locally (e.g. `swisspost/design-system/.github/actions/setup-pnpm@main` -> `./.github/actions/setup-pnpm`)
- [x] Add `packages/documentation/netlify.config.json` -> { siteId: `edc7287b-ec63-423c-84aa-c2a1cffbcf87`, siteUrl: `design-system.post.ch` }
- [x] Update `deploy-documentation.yaml` workflow to use the `netlify.config.json` data as input (see [example](https://github.com/swisspost/design-system/pull/2985/files#diff-241043eedcdf515d246604d4b88b9803b15ffd75b18f533518738c876bcb3b39))
- [x] Add `packages/documentation/public/_redirects` file.
- [ ] Update new `release.yaml` from [here](https://github.com/oliverschuerch/design-system/blob/main/.github/workflows/release.yaml). Edit the necessary parts:
- [ ] `Collect Release Data`, `old.siteUrl` -> `design-system-version-${oldMajor}`
- [ ] `Create & Deploy Netlify Site`, `--account-slug` -> `OSS fromSwiss Post`
- [x] Update `release-documentation.yaml` to use `netlify.config.json` data
```
