### ISSUE TITLE
Remove deprecated accent colors

### ISSUE THREAD

**Issue by davidritter-dotcom** [swisspost/design-system#3227]
Accent colors are deprecated and should not be used anywhere in the system (example: https://design-system.post.ch/?path=/docs/eb78afcb-ce92-4990-94b6-6536d5ec6af4--docs#accent-colors).

- [x] Remove accent colors from the styles package
- [x] Check documentation and remove any references to accent colors

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/3497
```
