### ISSUE TITLE
[component]: tooltip test

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3240]
### Description

test

### Design

https://google.ch

### Tokens

- [X] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```
