### ISSUE TITLE
[component]: Text input

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3270]
### Description

Create a HTML/CSS component using the current markup that implements as many features as possible from the new Design. Remove any dependencies on bootstrap for this component. This is done for backwards compatibility reasons. The current structure will eventually be deprecated. These styles will give us the necessary time to come up with a solid input component strategy.

### Open issues:
**Design:**
- [x] Integrated and tested new Typography
- [x] Integrated new Icons
- [ ] Spacing is defined

**Tokens:**
- [x] text

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=21-168

### Tokens

- [X] Tokens for this component are ready
Depends on #3402 

```scss
@use 'sass:map';
@use './../tokens/components' as tokens;

// to see the available component tokens
@each $key in map.keys(tokens.$post-text-input) {
  @debug $key;
}

input {
  {property}: map.get(tokens.$post-text-input, {token-name});
}
```

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review figma design (states complete, ability to implement)
- [x] HTML/CSS implementation
- [x] Remove any references to bootstrap
- [x] Remove any unused scss variables for this component
- [x] Documentation in Storybook
- [x] Visual regression tests
- [x] Design review
```

**Comment by gfellerph** [comment]
After discussion with @sandrahohl-post, small variants and dark mode will be added in a later iteration.

**Comment by gfellerph** [comment]
Open point: validation message (create a component? is icon in validation message?)

**Comment by Cian77** [comment]
Integrated new Typography and Icons.

**Comment by alizedebray** [comment]
Waiting for the new tokens.

**Comment by oliverschuerch** [comment]
@alizedebray would it be ok to move this ticket to "Ready for tokenisation" again and assign it to @Vandapanda (without unassign yourself)?
@Cian77 will update the integration of the text input in Figma and let us know, as soon as @Vandapanda can work on it again.

**Comment by Vandapanda** [comment]
Assigned @Cian77 as its in redesign atm. Would recommend to move it to "Design in Progress" as its not ready for tokenisation right now if thats fine with you @alizedebray

**Comment by gfellerph** [comment]
New Design is approved.
