### ISSUE TITLE
[component]: Select

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3271]
### Description

Create a HTML/CSS component using the current markup that implements as many features as possible from the new Design. Remove any dependencies on bootstrap for this component. This is done for backwards compatibility reasons. The current structure will eventually be deprecated. These styles will give us the necessary time to come up with a solid input component strategy.

### Open issues:
**Design:**
- [ ] New font
- [ ] Spacing

**Tokens:**
- [x] Text

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=21-183

### Tokens

- [ ] Tokens for this component are ready

### Token proposal
- select-bg (enabled/disabled)
- select-fg (enabled/hover/focus/disabled)
- select-border (width/style/color) (enabled/hover/focus/disabled)
- select-border-radius
- select-padding-inline
- select-padding-block (empty/filled)
- select-block-gap (space between value and label)
- select-label-font (size) (empty/filled)
- select-value-font-size
- select-focus (offset/width/style/color)
- select-validation-icon-size
- select-controls-gap (space between chevron and validation icon)

Validation colours should come from validation component.

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review figma design (states complete, ability to implement)
- [x] HTML/CSS implementation
- [x] Remove any references to bootstrap
- [x] Remove any unused variables for this component
- [x] Variants: single select, multiselect (design not in figma, style manually, will be like a list box)
- [x] Documentation in Storybook
- [x] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Implement styles as close as possible, a ticket for a custom select web component will follow.
