### ISSUE TITLE
[component]: Textarea

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3272]
### Description

Create a HTML/CSS component using the current markup that implements as many features as possible from the new Design. Remove any dependencies on bootstrap for this component. This is done for backwards compatibility reasons. The current structure will eventually be deprecated. These styles will give us the necessary time to come up with a solid input component strategy.

### Open issues:
**Design:**
- [x] New font
- [x] New Icons
- [ ] Spacing

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=21-182

### Tokens

- [x] Tokens for this component are ready

### Tokens proposal
- textarea-bg (enabled/disabled)
- textarea-fg (enabled/hover/focus/disabled)
- textarea-border (width/style/color) (enabled/hover/focus/disabled)
- textarea-border-radius
- textarea-padding-inline
- textarea-padding-block (empty/filled)
- textarea-block-gap (space between value and label)
- textarea-label-font (size) (empty/filled)
- textarea-value-font-size
- textarea-focus (offset/width/style/color)
- textarea-validation-icon-size
- textarea-min-height (for distinguishing between a text input)
- textarea-indicator-font (size) (that little 0/300 char limit indicator)

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review figma design (states complete, ability to implement)
- [x] HTML/CSS implementation with Design Tokens
- [x] Remove any references to bootstrap
- [x] Remove any unused component scss variables
- [x] Documentation in Storybook
- [x] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Discussion with @sandrahohl-post, small variants and dark mode will be added in a later stage.

**Comment by sandrahohl-post** [comment]
Added assistive text, FYI @gfellerph

**Comment by Cian77** [comment]
Integrated new Typo and Icons.

**Comment by gfellerph** [comment]
Discuss about how to style native elements only.

**Comment by oliverschuerch** [comment]
[Scrollbar styling](https://caniuse.com/css-scrollbar) could be a thing in the future, to keep a consistent width of the scrollbar in all the browsers. Anyway, the team decided, to go with the native scrollbar styles (defined by the browsers), for the moment and think about this possibility later.

**Comment by leagrdv** [comment]
@Vandapanda tokens update needed:
- The placeholder color is missing (right now it's using "disabled-fg" but it should be its own token: textarea-placeholder-fg
- Distance from validation icon to the right of the field is not tokenized, 
- Some other tokens are missing: "Value" padding top and padding left; "Label" (filled) padding top, left and right;  "Label" (empty) padding top, left and right

Overall, a lot has changed in the structure in order to update the validation icons position and it broke the tokens a bit

**Comment by rouvenpost** [comment]
Design Review approved.
