### ISSUE TITLE
[component]: Checkbox

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3273]
### Description

Create a HTML/CSS component using the current markup that implements as many features as possible from the new Design. Remove any dependencies on bootstrap for this component. This is done for backwards compatibility reasons. The current structure will eventually be deprecated. These styles will give us the necessary time to come up with a solid input component strategy.

### Open issues:
**Design:**
- [ ] New font
- [ ] Spacing

**Tokens:**
- [ ] text

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=18-14

### Tokens

- [x] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Review Design (All states present? Possible to implement?)
- [ ] #3496
- [ ] https://github.com/swisspost/design-system/issues/3274
- [x] HTML/CSS implementation
- [ ] Remove all unused scss variables for this element
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by schaertim** [comment]
@sandra-post ready for design review :)
