### ISSUE TITLE
[foundations]: Grid

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3276]
### Open issues:

**Tokens:**
- [ ] Grid 

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=26-51

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Create a POC to discover any possible issues with the breakpoints and/or tokens
- [x] CSS implementation
- [x] Documentation in Storybook
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
As discussed today, implement breakpoints component tokens that have separate breakpoints for grid (XS, SM, MD, LG, XL) and components (Mobile, Tablet, Desktop).

**Comment by alizedebray** [comment]
New resolution: https://github.com/orgs/swisspost/projects/3/views/47?pane=issue&itemId=81612717
