### ISSUE TITLE
[component]: Breadcrumb item

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3277]
### Description
Single link in the breadcrumbs linklist. Needs to be nested inside `<post-breadcrumbs>`.

### Open issues:
**Design:**
- [ ] New font
- [ ] Spacing

**Tokens:**
- [ ] Text

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=558-16158

### Tokens

- [x] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Web component implementation
- [x] Update checkUrl function from components/src/utils/property-checkers
- [ ] Design review
```
