### ISSUE TITLE
[component]: Popover

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3278]
### Open issues:
**Design:**
- [ ] New font
- [ ] Spacing

**Tokens:**
- [x] Text

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=21-173

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Define more generic tokens
- [ ] Update styles with tokens
- [ ] Documentation in Storybook
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
There is an existing PR, but the tokens need re-specification for this component (some of them are way too specific) and the component styles in the existing PR require a re-work.

**Comment by gfellerph** [comment]
@Vandapanda content does not need to be tokenised, just padding, border-radius, etc.
