### ISSUE TITLE
[tokens]: setup device semantic layer styles

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3306]
### Description

Set up `_devices.scss` that imports the semantic tokens for the device layer and wraps the tokens in appropriate media queries. This file is intended to be `@use`'d by other output files, so should not be compiled on it's own and should not contain any other styles than the tokens.

**Notes**: 
Don't wrap the styles for mobile in a media query so they'll serve as default styles (mobile first).

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] https://github.com/swisspost/design-system/pull/3285
- [ ] https://github.com/swisspost/design-system/pull/3262
- [x] Create the `_devices.scss` file
```
