### ISSUE TITLE
[tokens]: set up modes semantic layer

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3308]
### Description

Set up a `_modes.scss` file which uses the semantic tokens from the modes layer. This file is intended to be `@use`'d by other output files, so should not be compiled on it's own and should not contain any other styles than the tokens.

**Notes**:
Don't wrap the light mode styles in a query, they are the default styles.

**Selectors for light mode**:
- `[data-color-mode="light"]`

**Selectors for dark mode**:
- `[data-color-mode="dark"]`

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] https://github.com/swisspost/design-system/pull/3285
- [ ] https://github.com/swisspost/design-system/pull/3262
- [x] Create placeholders for light and dark mode CSS variables
- [x] Create the `_modes.scss` file
```
