### ISSUE TITLE
[tokens]: Create new output file combinations for channel & theme tokens

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3312]
### Description

New output file combinations are necessary to handle tokens. Create output files for each theme/channel combination, following the schema `[theme]-[channel].scss`. 

- `post-external.scss`
- `post-internal.scss`

**Notes**:
Sample imports for `post-external.scss`:

```scss
// Semantic layer (order needs to be tested, should match the order in Token Studio)
@use "/tokens/_modes";
@use "/tokens/_devices";
@use "/tokens/_external";
@use "/tokens/_post-theme";

@use "/components";
```

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Create output files
- [ ] import post-external.scss from index.scss
- [ ] import post-internal.scss from intranet.scss
```
