### ISSUE TITLE
Release v8

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3322]
```[tasklist]
### Tasks
- [ ] Spend 1h to try to fix e2e tests (collapsible)
- [x] Merge all PRs with the v8 label https://github.com/swisspost/design-system/pulls?q=is%3Aopen+is%3Apr+label%3Av8
- [x] Release v8 by merging https://github.com/swisspost/design-system/pull/3309
```

**Comment by gfellerph** [comment]
Closing without spending time on fixing e2e tests (no capacity)
