### ISSUE TITLE
Prepare for v9

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3323]
Version 9 will start as an alpha version. This means that releases will already happen, but under an alpha flag. This will enable projects like the Post Portal to already use the new styles before migration docs and everything else are ready. Alpha (or any other tagged packages) need to be installed using `npm install @swisspost/design-system-styles@alpha`. 

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/3322
- [x] Create a major changeset for v9
- [x] Enter pre-release mode with the changeset config https://github.com/changesets/changesets/blob/main/docs/prereleases.md
```
