### ISSUE TITLE
Sass: fix deprecated mixed declarations

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3344]
We're receiving the following deprecation warning when building our styles. Mixed declarations are being deprecated to match CSS behavior in the future. More info: https://sass-lang.com/documentation/breaking-changes/mixed-decls/

```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the 
declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
```

```[tasklist]
### Tasks
- [x] Check the warnings and update code to match new behavior
```

```[tasklist]
### Tasks
- [ ] #3732
- [ ] #3733
- [ ] #3734
- [ ] #3735
- [ ] #3736
- [ ] https://github.com/swisspost/design-system/pull/3742
- [ ] #3737
- [ ] https://github.com/swisspost/design-system/pull/3738
- [ ] https://github.com/swisspost/design-system/pull/3739
- [ ] https://github.com/swisspost/design-system/pull/3741
- [ ] https://github.com/swisspost/design-system/issues/3867
```
