### ISSUE TITLE
[component]: Custom text input

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3351]
### Description

Create a custom text input web component.

### Requirements
- Can have pre- and postfix text (see https://css-tricks.com/auto-growing-inputs-textareas/#aa-other-ideas for ideas on how to auto-grow input fields and textareas)
- Slots for input and label text (maybe someone wants to add (*) to required fields and the star needs to be red or add an info bubble with tooltip/popover -> slot needed instead of a prop)
- Label and input both need to live in the light dom since cross shadow root aria is not a thing yet, but the wrapper web component can help connecting the two with an id/for if it's not already done
- Slot for an icon or action button for datepicker on the right side
- Validation states/icons

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=21-168

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Review Design (All states present? Possible to implement?)
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by oliverschuerch** [comment]
Have a look at the [POC](https://design-system-v2-form-controls.netlify.app/), which has been done for this.
