### ISSUE TITLE
[component]: Badge

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3362]
### Open issues:
**Design:**
- [ ]  New font

**Tokens:**
- [ ]  text

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=17-162

### Tokens

- [X] Tokens for this component are ready

### Proposed structure

The badge can easily be an HTML/CSS only component, but there is no dedicated HTML element for this kind of information. According to proposals in https://github.com/swisspost/design-system/discussions/3287, this element would use a custom name. Depending on the context, `aria-live` support for incoming messages would be necessary (but not provided by the badge).

```html
<post-badge>Content</post-badge>

<post-badge class="bg-yellow">Yellow content</post-badge>
```

### Tasks

```[tasklist]
### 🎨 Design
- [ ] Design component according to WIKIT
- [ ] Update dependencies
- [ ] Add & test compo in layout examples
- [ ] Designer review
- [x] Documentation: Overview and usage (About, compo overview, compo props, usage, examples)
- [x] Documentation: Technical documentation (Anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by Cian77** [comment]
Hi Philipp, we can close this ticket, I have postponed this component, as we don't have a use case for it just now.

**Comment by gfellerph** [comment]
Closing in favour of https://github.com/swisspost/design-system-planner/issues/1
