### ISSUE TITLE
[component]: Banner (notification)

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3379]
### Open issues:
**Design:**
- [x] New font
- [ ] Icons might change slightly
- [x] Layout & Elevation

**Tokens:**
- [x]  text

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=1447-8848&t=hi5Lhfxq6GCN6B50-4

### Tokens

- [x] Tokens for this component are ready

DEVs proposal
Token set name: Components/Banner

Title and text styles (expect from the color) should come from the base styles (`.h4` for the title, `<p>` for text).
The close button is or will be a standalone CSS component (styled with `post-close-...`) and therefore must not provide tokens in the `banner` component.
Also the button styles/tokens should not be part of this component.

- `post-banner-padding`
- `post-banner-bg`
- `post-banner-fg`
- `post-banner-border-width`
- `post-banner-border-style`
- `post-banner-border-color`
- `post-banner-border-radius`
- `post-banner-gap` (gap between icon and content)
- `post-banner-icon-size`
- `post-banner-icon-bg`
- `post-banner-content-gap` (block-gap between content elements)
- `post-banner-actions-margin-top`
- gap between buttons will be handled in the spacing topic

### Requirements
- Variants: The banner can be inline on the page (system disruption/maintenance warning) or can be used as a modal dialog with a backdrop blocking interactions on the page
- As stated in https://github.com/swisspost/design-system/issues/3608#issuecomment-2388730662, we're not going to tokenise the button responsive behaviour.

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [ ] https://github.com/swisspost/design-system/issues/3697
- [ ] https://github.com/swisspost/design-system/issues/3492
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [x] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Work in progress on the Design.

**Comment by gfellerph** [comment]
**Resolution**: Banner can be used as a modal and inline in the page and a neutral background color can be used in addition to the four signal colours.

- [ ] Provide an example of the modal banner in Figma to define the backdrop

**Comment by rouvenpost** [comment]
I added the «Neutral» Variant to Inline notification, Snackbar, Toast & Banner

**Comment by Vandapanda** [comment]
Tokenized. removed FG tokens as those will be taken from body. defined the bg-scheme for each color variant. Actions gap can be removed once spacing is defined over all components correctly

**Comment by leagrdv** [comment]
Discussed with Rouven, we keep the current dialog backdrop (rgba(0,0,0,0.8) with a blur)
