### ISSUE TITLE
[component]: Skiplinks

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3391]
Migrate the skiplinks component to the components package from it's current place in the internet header package.

**Design**: Keep as is

### Proposed structure
```html
<div class="skiplinks">
  <a href="#navigation">Navigation</a>
  <a href="#main">Main</a>
</div>
```

### References
- https://accessibility.oit.ncsu.edu/using-aria-landmarks-a-demonstration/#:~:text=WHAT%20ARE%20ARIA%20LANDMARKS%3F,%E2%80%9Cskip%20to%20main%20content%E2%80%9D.

```[tasklist]
### Tasks
- [x] Create the HTML/CSS component Skiplinks
- [x] Add storybook documentation
- [x] Add/port e2e tests
```
