### ISSUE TITLE
[foundations]: Typography >Heading H1 - H6

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3414]
### Description

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [ ]  Spacing is defined
- [ ] Documentation final

**Tokens:**
- [x]  Typography tokens ready

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=26-49

### Tokens

- [x] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [ ] https://github.com/swisspost/design-system/issues/3496
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by Vandapanda** [comment]
H1-H6 adjusted according to the documentation. Exceptions have not yet been recorded as it is not entirely certain whether and how necessary. Fonts could be revised again as discussed on 26.08.24.
