### ISSUE TITLE
[foundations]: Typography >Legend

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3415]
### Description

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [ ]  Spacing is defined
- [ ] Documentation final

**Tokens:**
- [x]  Typography tokens ready

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=26-49

### Tokens

- [x] Tokens for this component are ready

### Proposed component structure

```html
<fieldset>
  <legend post-size="large"> <!-- Discuss about property naming for native elements -->
    Large legend
    <button class="btn btn-icon"><post-icon name="info"></post-icon>Weitere infos</button>
  </legend>

  <fieldset>
    <legend>Default legend</legend>
  </fieldset>
</fieldset>


```

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [ ] https://github.com/swisspost/design-system/issues/3496
- [ ] Remove any unused scss variables for this element
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Design review
```
