### ISSUE TITLE
[foundations]: Typography > Paragraph

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3416]
### Description

Implement default styles paragraphs.

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [x]  Spacing is defined
- [ ] Documentation final

**Tokens:**
- [x]  Typography tokens ready

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=26-49

### Tokens

- [x] Tokens for this component are ready

### Proposed markup
```html
<p class="lead">This is a lead text</p>

<!-- With tokens, paragraphs in different dimensions will have different sizes -->
<p>This is a default paragraph (medium)</p>

<!-- Don't implement size variants for large or small paragraphs. Font size for other use cases will be determined by either the wrapping component or utility classes -->
```

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [ ] https://github.com/swisspost/design-system/issues/3496
- [x] Remove all unused scss variables for this element
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [ ] Design review
```

**Comment by oliverschuerch** [comment]
@bashirkarimi Take care! As far as I understand, we decided paragraph tyles will end up in a `elements/paragraph.scss` while lead styles will end up in `components/lead.scss`.
Maybe we should split this tickets into two different tickets.

**Comment by oliverschuerch** [comment]
I have just added another ticket for the lead text component: #3546
