### ISSUE TITLE
[foundations]: Labels

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3417]
### Description

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [ ]  Spacing is defined
- [ ] Documentation final

**Tokens:**
- [ ]  Typography tokens ready

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=26-49

### Tokens

- [ ] Tokens for this component are ready

**DEVs proposal**
Base styles: `body`
Token set name: `Element/Label`
- `post-label-font-weight` (Label large bold (default))
- `post-label-gap-block-start` https://github.com/swisspost/design-system/labels/needs%3A%20discussion
- `post-label-gap-block-end` https://github.com/swisspost/design-system/labels/needs%3A%20discussion

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Review Design (All states present? Possible to implement?)
- [ ] https://github.com/swisspost/design-system/issues/3496
- [ ] Use generic typography tokens from the elements collection
- [ ] HTML/CSS implementation
- [ ] Check if documentation is still ok
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Default label styles can be inherited from the body. Other label variants are used in specific contexts, so the context should provide the overrides. Do we even need specific label styles or is it pure overhead?

-> If we define default label styles using the tokens, we'd get style changes to the default label without any change, but as long as the label has the same styles as default text, we'd ship code that does not do anything.

**Comment by gfellerph** [comment]
@oliverschuerch please add information about what's needed from token side

**Comment by oliverschuerch** [comment]
We will not create tokens to use in code for this. As @gfellerph described, these text styles are used in different contexts (buttons, inputs, etc.). and will be tokenized there, per component.

There might be some FigmaOnly typography tokens for this, to simplify things in Figma, but that's all.

@Cian77 we will also not provide the possibility to use those styles through utility css-classes, because we don't think this should be possible. Do you agree?

If @Cian77 agrees to the above question, we can close this issue.

**Comment by Vandapanda** [comment]
@oliverschuerch @gfellerph @Cian77 Task unclear, can we close the ticket now or is there more needed? Ticket seems not ready for tokenization.

**Comment by Vandapanda** [comment]
Closed according to discussion, no specific label tokens will exist. Instead each Component uses its own token.
