### ISSUE TITLE
[component]: Text highlighted

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3419]
### Description

Text highlighted can be used when a certain paragraph needs a higher attention than the other paragraphs. 

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [ ]  Spacing is defined
- [ ] Documentation final

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=1481-12917

### Tokens

- [x] Tokens for this component are ready
```scss
@use '../tokens/components' as components;
@use '../functions/tokens' as tokens;

tokens.$default-map: components.$post-text-highlighted;

.text-highlight {
  background-color: tokens.get('text-highlight', 'bg');
}

```

### Proposed markup
```html
<p class="text-highlighted"></p>
```

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [ ] https://github.com/swisspost/design-system/issues/3496
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
@oliverschuerch add map that is needed
