### ISSUE TITLE
[component]: Form Footer

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3420]
### Description

The form footer is placed at the end/bottom of a form or a form step, in case the form is splitted with a stepper. It provides workflow-related actions to the form or form step.

**Open issues:**

**Design**: 
- [ ]  Integrated new typography
- [ ]  Spacing is defined
- [ ] Documentation final

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=1498-28215

### Tokens

- [ ] Tokens ready 

### Tasks

This Design can be composed by using a combination of base components and utility classes. Document this under patterns.

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [x] Documentation in Storybook
- [x] Design review
```
