### ISSUE TITLE
[component]: App store badge

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3422]
### Description

Create a CSS component for an app store badge.

### Proposed markup

```html
<a href="https://link-to-your.app" class="app-store-badge">
  <img src="/local-assets/google.png" alt="" />
  Download the Post App on Google Play
</a>
```

- Size of the image should be defined
- Projects need to provide the app store badge locally (because of localization and requirement to keep the badge up to date)
- A descriptive text should be provided for the link

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [ ]  Spacing is defined
- [x] Documentation final

**Tokens:**
- [x]  Typography tokens ready

_No response_

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=1530-32646

### Tokens

- [x] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [x] Add tokens for height
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [x] Write documentation about where to download the latest badge image assets
- [x] Visual regression tests
- [ ] Design review
```

**Comment by Vandapanda** [comment]
@alionazherdetska You can find the tokens now under Components/App store button. There is no border radius for focus as its set to 6 right now while the normal component has 4. I assume it will just be handled like everything else and get the border radius from the component itself, if anything changes I'll message you
