### ISSUE TITLE
[component]: Text link

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3424]
### Description

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [ ]  Spacing is defined
- [x] Documentation final

**Tokens:**
- [x]  Typography tokens ready

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=2016-47948

### Tokens

- [x] Tokens for this component are ready

DEVs proposal
Base styles: `body`
Token set name: `Elements/Link`

- `post-link-decoration` (underline)
- `post-link-border-radius` (focus border-radius)
- `post-link-hover-fg`
- `post-link-focus-outline-width` (focus stroke width)
- `post-link-focus-outline-style` (focus stroke style)
- `post-link-focus-outline-color` (focus stroke color)
- `post-link-focus-outline-offset` (padding on Figma layer `Focus`)

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [ ] https://github.com/swisspost/design-system/issues/3496
- [x] Remove all unused scss variables for this element
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [ ] Design review
```
