### ISSUE TITLE
[helpers]: Palettes

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3432]
### Description

Classes to allow user to set a color set on any HTML section.

### Design

There is no design for the helpers.

### Token proposal

- post.palette.brand.fg
- post.palette.brand.bg
- post.palette.brand.bg-scheme
- post.palette.accent.fg
- post.palette.accent.bg
- post.palette.accent.bg-scheme
- post.palette.default.fg
- post.palette.default.bg
- post.palette.default.bg-scheme
- post.palette.alternate.fg
- post.palette.alternate.bg
- post.palette.alternate.bg-scheme

### Tasks

```[tasklist]
### 💻 Tasks
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [x] Visual regression tests
```

**Comment by oliverschuerch** [comment]
Depends on #3557

**Comment by gfellerph** [comment]
Does a specific surface also hold information if it's on a light or dark background? I think this needs some more discussion with Design and a better strategy on how we want to implement it.

**Comment by alizedebray** [comment]
@Vandapanda can you please rename "palette" to "palette**s**" to align with other sets and also add tokens for all theme/schemes (post-light, post-dark, cargo-light, cargo-dark)? Even if the colors are not correct for now, otherwise I get undefined token errors. Thanks!

**Comment by Vandapanda** [comment]
@alizedebray Changed the namings accordingly and will get pushed in a few hours. For the 2nd request I'm kind of missing some context. As it is right now the colors automatically change based on what canvas is used as they are rooted through scheme and theme. Do you need them hardcoded?

**Comment by alizedebray** [comment]
@Vandapanda 
Currently we have this tokens: 
![Image](https://github.com/user-attachments/assets/3e29696d-3cd4-4379-944c-1621d871605c)

And we would need to have this: 
![Image](https://github.com/user-attachments/assets/9e89c366-291f-4dd6-95d0-111e1fcc5317)

**Comment by alizedebray** [comment]
Latest state: 
![Image](https://github.com/user-attachments/assets/bcc0ffe0-76d2-41e1-aae6-ea1c04fdd926)
