### ISSUE TITLE
[component]: Sizing utilities

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3433]
### Description

Simple classes to allow users to set the height, width, max-height, and max-width (and potentially min-height, min-width) of any HTML element. Provide utility classes for the percentages 25, 50, 75 and 100.

https://design-system.post.ch/?path=/docs/e728de1f-0d71-4317-8bb8-cbef0bf8d5db--docs

### Design

There is no design for the utilities.

### Tokens

We do not implement tokens for these utility classes.

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [x] HTML/CSS implementation
- [x] Remove any references to bootstrap
- [x] Documentation in Storybook
- [x] Visual regression tests
```

**Comment by myrta2302** [comment]
Issue: Generated breakpoints classes are in some cases overridden by simple classes (e.g. h-xl-0)
