### ISSUE TITLE
[component]: Spacing utilities

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3434]
### Description

Simple classes to allow users to set padding, margins, and gaps on any HTML element.

### Design

There is no design for the utilities.

### Tokens

- [x] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [x] Visual regression tests
```

**Comment by alizedebray** [comment]
@Vandapanda I just created the margin, padding, and gap utilities using these tokens: https://github.com/swisspost/design-system/blob/fdd21ce7954260859aae0230168bf2583016d4ea/packages/styles/src/utilities/temp/_tokens.scss

Would it be possible to rename the tokens accordingly in Token Studios?
Thank you!
