### ISSUE TITLE
Playground for responsive icons

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3435]
```[tasklist]
### Tasks
- [x] Create a playground for responsive icons
- [x] Tryout using an icon sprite and the svg use tag.
- [x] Try out container queries to switch between responsive icon variants
```

https://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/
