### ISSUE TITLE
[component]: Check list

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3438]
### Description
Create a unordered list variant that has checkmarks as bullet points. Keep in mind, that text and bullet size is dependent on the font-size of surrounding text.

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [ ]  Spacing is defined
- [x] Documentation final

**Tokens:**
- [ ]  Typography tokens ready

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=21-170

### Tokens

- [x] Tokens for this component are ready

### Proposed markup
```html
<ul class="list-checks">
  <li>...</li>
</ul>
```

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [ ] https://github.com/swisspost/design-system/issues/3496
- [ ] #3437
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by oliverschuerch** [comment]
Wait for the native (simple) lists to be ready/tokenized/implemented!

**Comment by Vandapanda** [comment]
@bashirkarimi I moved the Tokens for Checks list into a Set on its own to differentiate between simple list and the normal list. Therefore the Set name for those Token was changed from Components/List to Components/List Simple. Every other naming stayed the same but this might mean that you have to touch the code again (not sure if you have the Set name in there)

**Comment by myrta2302** [comment]
@Vandapanda 
  post-list-check-sizing-icon: 32px,
  post-list-check-text-padding: 1px,
  post-list-check-icon-gap-inline: 16px,
  post-list-check-item-gap-block-text: 16px,
  post-list-check-margin-block: 8px,
  post-list-check-color-icon-fg: white,
  post-list-check-color-text-fg: #050400,
  post-list-check-padding-icon: 4px,
  post-list-check-line-height: 30px
