### ISSUE TITLE
[component]: List with Links

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3447]
### Description

Create a list with links standalone HTML/CSS component (relevant discussion https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR?node-id=2613-2621#933519392).

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [ ]  Spacing is defined
- [ ] Documentation final

**Tokens:**
- [ ]  Typography tokens ready

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=21-170

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Don't forget to add the slight animation of the arrow on hover/focus
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by alizedebray** [comment]
Closing as duplicates of [#3658](https://github.com/swisspost/design-system/issues/3658)
