### ISSUE TITLE
Create token maintainer documentation

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3448]
As discussed in #3371 and #3401 we should create a documentation for people working on the token system in Figma.

```[tasklist]
### Tasks
- [ ] Generic infos on tokens (references to other token systems, w3c community group, ...)
- [ ] Tokens @ Swiss Post (Architecture, Goal, Overview, Token Studio ...)
- [ ] Installation instructions (GitHub Token, How to push/pull, link to GitHub branch)
- [ ] Process sketch (#3382)
- [ ] Naming scheme (#3356)
- [ ] Token rules (#3371)
```

**Comment by sandra-post** [comment]
Copied content of following issues to [WIKIT](https://wikit.post.ch/spaces/CW/pages/2209613114/Design+Tokens) in order to have all tokens documentation in one place:
- [#3371 Token Guidelines](https://github.com/swisspost/design-system/issues/3371)
- [#3356 Component Token Naming](https://github.com/swisspost/design-system/issues/3356)
