### ISSUE TITLE
[component]: Dropdown single select

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3452]
### Description

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [ ]  Spacing is defined
- [x] Documentation final

**Tokens:**
- [x]  Typography tokens ready
```yml
post.dropdown.single-select.menu.padding.block: post.device.spacing.padding.block.8
post.dropdown.single-select.menu.border-radius: post.device.border-radius.1
post.dropdown.single-select.menu.elevation: post.device.elevation.300

post.dropdown.single-select.menu.category-title.padding.block.outer: post.device.spacing.padding.block.14
post.dropdown.single-select.menu.category-title.padding.block.inner: post.device.spacing.padding.block.15
post.dropdown.single-select.menu.category-title.padding.inline.inner: post.device.spacing.padding.inline.3
post.dropdown.single-select.menu.category-title.enabled-fg: post.scheme.color.interactive.primary.enabled.fg1
post.dropdown.single-select.menu.category-title.stroke: post.scheme.color.interactive.primary.enabled.stroke
post.dropdown.single-select.menu.category-title.font-weight: post.device.font-weight.bold

post.dropdown.single-select.menu.list-item.padding.block.start: post.device.spacing.padding.block.16
post.dropdown.single-select.menu.list-item.padding.block.end: post.device.spacing.padding.block.17
post.dropdown.single-select.menu.list-item.padding.inline.start: post.device.spacing.padding.5
post.dropdown.single-select.menu.list-item.padding.inline.end: post.device.spacing.padding.inline.4
post.dropdown.single-select.menu.list-item.gap.inline.text-start: post.device.spacing.gap.4

post.dropdown.single-select.menu.list-item.enabled-fg: post.scheme.color.interactive.primary.enabled.fg1
post.dropdown.single-select.menu.list-item.hover-fg: post.scheme.color.interactive.primary.hover.fg1
post.dropdown.single-select.menu.list-item.enabled-bg: post.scheme.color.interactive.primary.enabled.bg1
post.dropdown.single-select.menu.list-item.hover-bg: post.scheme.color.interactive.primary.hover.bg
post.dropdown.single-select.menu.list-item.hover-stroke: post.scheme.color.interactive.primary.hover.stroke
post.dropdown.single-select.menu.list-item.enabled-stroke: post.scheme.color.interactive.primary.enabled.stroke3

post.dropdown.single-select.menu.list-item.border-width.bottom: post.device.border-width.alternative2

post.dropdown.single-select.menu.list-item.icon.spacing.height.outer: post.device.sizing.icon.2

post.dropdown.single-select.menu.list-item.icon.size: post.device.sizing.interactive.icon.size

```

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=21-167

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```
