### ISSUE TITLE
[component]: Social media buttons

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3458]
### Description

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [ ]  Spacing is defined
- [ ] Documentation final

**Tokens:**
- [ ]  Typography tokens ready

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=1531-34749

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
- [ ] https://github.com/swisspost/design-system/issues/3492
```

**Comment by gfellerph** [comment]
**Resolution**: @Cian77 is going to check if we can re-use in the footer.

**Comment by gfellerph** [comment]
Closing in favour of #3461, use icon buttons instead of creating a separate component.
