### ISSUE TITLE
[component]: Footer

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3461]
### Description

**Open issues:**

**Design**: 
- [x]  Integrated new typography
- [ ] Design review 20. Sept. 20
- [ ]  Spacing is defined
- [ ] Documentation review 
- [ ] Documentation final

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=558-7013

### Tokens

Header and footer will not be tokenized at this time.

### Requirements
- On mobile, the link lists should be wrapped by an accordion
- Almost all elements are optional, the only required elements are the imprint/accessibility links and the copyright information
- It should be easy to compose the footer with custom data, there should not be a different component structure for mobile and desktop (for developers), the accordion wrapping should happen internally
- Aria requirements have to be met, link lists need to be connected to their heading via `aria-labelledby`. If the heading is not visible, aria-label can be used as well (see https://www.figma.com/design/p5pBgXMdRs9eM2HzzeXh4z/Menus?node-id=2-7158&t=Mam0iMG60hAkbUrx-1 for more details)
- Heading levels should be configurable

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] https://github.com/swisspost/design-system/issues/3544
- [ ] https://github.com/swisspost/design-system/issues/3457
- [ ] https://github.com/swisspost/design-system/issues/3458
- [ ] https://github.com/swisspost/design-system/pull/3731
- [x] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS component implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
```
