### ISSUE TITLE
Remove the demo app

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3497]
The old Angular demo app can finally be removed from the monorepo. There are some dependencies that can be cleaned up along the way.

```[tasklist]
### Tasks
- [x] Remove the demo app package
- [x] Remove any github action that's connected to the demo app
- [x] Remove any reference to the demo app in other packages
- [x] Remove any mentions of the demo app in other documentation or contribution pages
- [x] Check if the demo app is mentioned on confluence and mark it as deprecated, update any links to point to https://archive.design-system.post.ch
```
