### ISSUE TITLE
Remove the intranet header workspace

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3498]
The intranet header workspace package can be removed for v9 and up. With it, also all documentation and references in other places should be removed.

```[tasklist]
### Tasks
- [ ] Remove the intranet-header workspace package and all it's subfolders from the repo
- [ ] Mark the @swisspost/design-system-intranet-header package as deprecated on npm with a reference to the new header that can be built with the components package
- [ ] Remove any mentions of the intranet header from documentation or contribution/security instructions
- [ ] Check for references to the intranet header on confluence and mark them as deprecated, update any URLs to https://archive.design-system.post.ch
```

**Comment by gfellerph** [comment]
On hold until new header can be used internally.

**Comment by oliverschuerch** [comment]
This (on v9) would fasten up our DEV environment and also reduce our github worklfows.
