### ISSUE TITLE
Remove global styles

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3543]
If we want to be able to see what we start to specify on basic HTML elements, we need to do the following steps first:

```[tasklist]
### Tasks
- [ ] Remove the bootstrap reset and implement our own. `elements/reset.scss` #3533
- [ ] Remove all files containing only global styles (reboot, fonts, etc.)
- [ ] Check if there are more global style definitions in other files which do not only implement global but also component specific files and decide if these definitions can be removed as well. Might be subject for a discussion.
- [ ] Make sure the styles package can still be builded, otherwise this change can not be merged!
```
