### ISSUE TITLE
[component]: List

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3544]
### Description

The `<post-list>` component is a very versatile component used throughout the header and footer and with various styles. A basic usage example could be

```html
<post-list>
  <h3>Parcel</h3>
  <post-list-item>
    <a href="/">Sending</a>
  </post-list-item>
  <post-list-item>
    <a href="/">Receiving</a>
  </post-list-item>
</post-list>
```

#### Shadow DOM 
This component does not make use of shadow dom because the parent list (the `<ul>` so to speak) is rendered by the component while the `<post-list-item>` lives in the light DOM. If the component used shadow DOM, the ul <> li relationship would have to cross the shadow boundary which is not possible at the moment

#### Styling options
There are two properties that need to be exposed for easy styles overrides
- `--post-list-item-gap`: Gap between list items
- `--post-list-direction`: Flex direction of the list
- `--post-list-heading-gap`: Gap between heading (if shown) and the list

These options need to have a default definition (coming from tokens) and need to be overridden by a user. To achieve this, the following styling can be used:

```css
:host {
  --post-list-gap: #{tokens.get("post-list-gap")}; // declare the custom property with a default value that can be overriden

  > div[role="list"] {
    gap: var(--post-list-gap); /* If this variable is defined (by the user), it will override the token, if it's not defined, the token will apply */
  }
}
```

### Props
- `title-hidden`: (naming proposals welcome) the internal title container gets the class `visually-hidden`

### Variants
- Title and vertical list: Title is visible, list is vertical (default)
- Horizontal list: Title is visible, list is horizontal by defining `<post-list style="--post-list-direction: row">` or something similar
- No title: Title is visually hidden `<post-list title-hidden>`
- Custom gap: `<post-list style="--post-list-gap: 1rem; --post-list-item-gap: 1rem 0.5rem">`

### Accessibility
Internally, the component needs to connect some things in order to be accessible.
- The list and the title have to be connected via `aria-labelledby`
- The heading or label can be visually hidden

### Benefits
- Users don't have to come up with ids to link up the list description and the list
- Basic orientation styling is in place and it's easily extensible

### Use cases
<img width="109" alt="image" src="https://github.com/user-attachments/assets/39b68291-9040-4952-aece-ee40d299ce79">
<img width="292" alt="image" src="https://github.com/user-attachments/assets/b28cf60f-08ae-4990-8440-576b77070dfe">
<img width="230" alt="image" src="https://github.com/user-attachments/assets/db18d5c6-8908-40ff-884b-2bf57ce850bf">
<img width="246" alt="image" src="https://github.com/user-attachments/assets/1ead9849-def5-4f66-8914-54652f4e2e52">
<img width="377" alt="image" src="https://github.com/user-attachments/assets/dd3d690f-1c2d-46ed-b82e-c52d96f1b1eb">
<img width="431" alt="image" src="https://github.com/user-attachments/assets/adadf082-708d-41c3-a02f-52be8de6f7a3">
<img width="129" alt="image" src="https://github.com/user-attachments/assets/2c567ba0-3e83-41d1-9d10-7d690f98e01c">
<img width="437" alt="image" src="https://github.com/user-attachments/assets/8eb658b3-0c51-47b0-b267-292cb42ed79e">
<img width="165" alt="image" src="https://github.com/user-attachments/assets/11b0505a-e886-4c0a-96dc-fc2f57b32a6c">
<img width="338" alt="image" src="https://github.com/user-attachments/assets/b52b5bc8-c111-4864-8bdd-27952304778f">
<img width="291" alt="image" src="https://github.com/user-attachments/assets/ddf6aa85-735a-4600-b6bf-0875d65eae75">

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=558-7013&t=tiW8c2NHXI0mcJa5-1

### Tokens

Tokens for HTML/CSS lists apply.

### Proposal for internal structure

```jsx
<Host> <!-- post-list -->
  <div id={this.uiid}>
    <slot></slot> <!-- main slot for label, heading -->
  </div>
  <div role="list" aria-labelledby={this.uiid}>
    <slot name="post-list-item"></slot> <!-- slot for auto-assigned list items -->
  </div>
</Host>

<Host role="listitem" slot="post-list-item"></Host> <!-- post-list-item -->
```

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Web component implementation
- [x] Documentation in Storybook
- [ ] Unit tests
- [x] End to end tests
- [x] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Needs refinement for doability and usefulness.
