### ISSUE TITLE
[lead text]: Add styles for the lead text component

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3546]
### Description

Implement lead text styles

#### Design
- [x] Integrated new typography
- [ ] Spacing is defined
- [ ] Documentation final

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=178-6713&node-type=frame&t=X3tyO53unPAPaH3B-0

### Tokens
- [x] Tokens for this component are ready

#### DEVs proposal

Base styles: `body`
Token set name: `Components/Lead`
- `post-lead-font-size` (D 24, T 20, M 18)
- `post-lead-font-weight` (700 or bold)

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Review Design (All states present? Possible to implement?)
- [ ] https://github.com/swisspost/design-system/issues/3496
- [x] Remove all unused scss variables for this element
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [ ] Design review
```
