### ISSUE TITLE
[component]: Link list

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3547]
# Description

Implement styles for the link list component

## Design
https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=30036-39980&node-type=frame&t=9S5ISrEjDt8dXCYT-0

- [x] Documentation final

## Tokens

- [ ] Tokens for this component are ready

```[tasklist]
## Tasks
- [ ] Review Design (All states present? Possible to implement?)
- [ ] #3496
- [ ] #3437
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Design review
```

**Comment by gfellerph** [comment]
Closing as duplicate of #3447
