### ISSUE TITLE
[component]: Action list

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3549]
# Description

Implement styles for the action list component

## Design
https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=30036-39980&node-type=frame&t=9S5ISrEjDt8dXCYT-0

- [x] Documentation final

## Tokens

- [ ] Tokens for this component are ready

```[tasklist]
## Tasks
- [ ] Review Design (All states present? Possible to implement?)
- [ ] #3496
- [ ] #3437
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Design review
```

**Comment by gfellerph** [comment]
@oliverschuerch the action list is a v1 component, v2 (https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=21-170&t=izqcOzdDOBrYeKW9-1) does not have this particular list anymore. Can we close this ticket?
