### ISSUE TITLE
[list]: Add styles for component switch list

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3550]
# Description

Implement styles for the switch list component

## Design
https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=30036-39980&node-type=frame&t=9S5ISrEjDt8dXCYT-0

- [x] Documentation final

## Tokens

- [ ] Tokens for this component are ready

```[tasklist]
## Tasks
- [ ] Review Design (All states present? Possible to implement?)
- [ ] #3496
- [ ] #3437
- [ ] Implement switch component
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Design review
```

**Comment by alizedebray** [comment]
Closing as duplicates of [#3658](https://github.com/swisspost/design-system/issues/3658)
