### ISSUE TITLE
Should we rename [data-color-mode] to [data-color-scheme]?

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3612]
For the tokens, we decided to call the dark/light layers "mode", however CSS refers to it as "color-scheme": https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

Should we align? 

If so we would need to: 

```[tasklist]
### Tasks
- [x] Rename modes.scss + placeholder
- [x] Rename semantic tokens
- [x] rename the [data-color-mode] attribute to [data-color-scheme]
- [x] Update the ThemeSwitcher storybook addon
- [x] Search for other color-mode namings and rename them
```

**Comment by gfellerph** [comment]
I'm all for aligning with the platform naming.

**Comment by gfellerph** [comment]
![Image](https://github.com/user-attachments/assets/f6efb729-82d1-4dd9-998a-be95e88d14f5)

**Comment by gfellerph** [comment]
@Vandapanda coordinate with devs when you start this one ❤️

**Comment by Vandapanda** [comment]
Changed to Scheme, forwarded to devs for the other points
