### ISSUE TITLE
Refactor the focus-styles mixin

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3622]
```[tasklist]
### Tasks
- [ ] Add a `$border-radius` input
- [ ] Fix the border-radius: because it is offsetted, the outline is rounder than it should be
- [ ] Make the `$additional-selector` the last input as it will not be used set in most cases
- [ ] (if possible) simplify the mixin so that you do not have to pass all parameters but only the token prefix
```

**Comment by gfellerph** [comment]
If we decide to unify focus styles (see Miro), we'd be able to refactor the mixin into it's own component.

**Comment by Vandapanda** [comment]
Added the helper class Focus and the above described token. Also added a border radius and inverted color just for figma. the later will be removed once we got the inversed component therefore they can be ignored by devs. Removed all other component token which will need to be fixed in code as well.
