### ISSUE TITLE
[component]: Main navigation

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3626]
Create a standalone usable version of the `<post-main-navigation>` component currently living in the internet-header package (https://github.com/swisspost/design-system/tree/main/packages/internet-header/src/components/post-main-navigation). At the moment, this component relies on a config file, this new component will be independent of the config. This component is first going to be used by the Post Portal only, therefore the first iteration can be tailored to be used in a next.js environment. A future version will be improved to be more interoperable and easier to use.

### Design
https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=558-7012&t=jcPdHnpzyiTuN0T3-1

![image](https://github.com/user-attachments/assets/9a1f04f3-17fb-4696-b82a-b3bc2da160c9)
![image](https://github.com/user-attachments/assets/26afd52d-ec4a-4b98-836d-f0d3445b6087)

### Props
- `caption`: Title of the navigation

### Requirements
- Top level link behaviour: On the top level, there can only be megadropdown-buttons or links. It's not possible like today to combine both (first tap opens megadropdown, second tap opens link). This should make the implementation somewhat easier
- Mobile behaviour: The main navigation component should behave roughly the same as today with the layered menu on mobile and the megadropdown on desktop
- Top level overflow behaviour: The links on the top level can overflow to the right (if someone was to put 1000 links there). This requirement could also be a candidate for the next iteration.
- Mobile overflow behaviour: Any linklist should be scrollable vertically
- All links and texts should be slotted as this version of the main navigation does not rely on any configuration file any more
- Tokens: for the time being, we're not tokenising any header components or styles

### Reference
- Current navigation https://www.post.ch/de

### Markup proposal

```html
<post-mainnavigation caption="Hauptnavigation">
  <button slot="back-button"><- Back</button>
 <post-list>
    <h2><a href="/privatkunden">Privatkunden</a></h2>
    <!-- Link only level 1 -->
    <post-list-item><a href="/briefe">Briefe</a></post-list-item>

    <!-- Level 1 with megadropdown -->
    <post-list-item>
      <post-megadropdown-toggle>
        Pakete
      </post-megadropdown-toggle>
      <post-megadropdown>
        <button slot="back-button"><- Zurück</button>
        <h2><a href="">Megadropdown title</a></h2>
        <post-list>
          <h3>Angebot</h3>
          <post-list-item><a href="/sch">Pakete Schweiz</a></post-list-item>
          <post-list-item><a href="/kl">Kleinwaren Ausland</a></post-list-item>
          <post-list-item><a href="">Waren Ausland</a></post-list-item>
          <post-list-item><a href="">Express und Kurier</a></post-list-item>
        </post-list>
        <post-list>
          <h3><a href="/schritt-für-schritt">Schritt für Schritt</a></h3>
          <post-list-item><a href="/sch">Pakete Schweiz</a></post-list-item>
          <post-list-item><a href="/kl">Kleinwaren Ausland</a></post-list-item>
          <post-list-item><a href="">Waren Ausland</a></post-list-item>
          <post-list-item><a href="">Express und Kurier</a></post-list-item>
        </post-list>
        <post-closebutton>Schliessen</post-closebutton>
      </post-megadropdown>
    </post-list-item>
  </post-list>
</post-mainnavigation>

<!-- post-mainnavigation -->
<Host>
  <nav aria-label=caption>
    <slot name="post-list"></slot>
  </nav>
</Host>
```

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/3544
- [ ] https://github.com/swisspost/design-system/issues/3697
- [ ] https://github.com/swisspost/design-system/issues/3764
- [ ] Create a `<post-main-navigation>` component
- [ ] Document this component in storybook
- [ ] Create e2e tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Component naming possibilities:
- post-main-navigation
- post-mainnavigation
- post-main-nav
- post-navigation
- post-megadropdown-navigation
