### ISSUE TITLE
Refactoring of form-check styles

### ISSUE THREAD

**Issue by schaertim** [swisspost/design-system#3628]
During the tokenisation of the form-check components I was unsure whether the styles for the switch, radio-button and checkbox should be separated (also different files?) to make them easier to understand.
```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/3275
- [ ] https://github.com/swisspost/design-system/issues/3537
- [ ] https://github.com/swisspost/design-system/issues/3273
```

**Comment by gfellerph** [comment]
@schaertim I would put them into separate files, this will also allow to conditionally import just one of the three.

**Comment by gfellerph** [comment]
**Resolution**: split it up
