### ISSUE TITLE
[component]: Validation

### ISSUE THREAD

**Issue by schaertim** [swisspost/design-system#3630]
It was decided that validation should be implemented separately and reused in all components requiring it. A dedicated token set has to be provided first.

### Design
https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=577-14513&t=uKEtTo9BEaPpKSV5-1

### Requirements
- Variants: Error or success message, with or without icon (exclamation- or checkmark, see [radiobutton list design](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=1737-14510&t=uKEtTo9BEaPpKSV5-4))
- Is linked to the input field via `aria-describedby` (by the user)
- Can be re-used by all components that need validation

```[tasklist]
### Tasks
- [x] Add HTML/CSS component implementation
- [x] Create separate Documentation
- [x] Visual Regression Test
- [x] Accessibility Test
- [x] Add new token set for validation
- [ ] Design review
```

**Comment by gfellerph** [comment]
@gfellerph add more information

**Comment by alizedebray** [comment]
- How should we handle the two different error message variants ? 
- How do we know which variant applies to which component ?

**Comment by gfellerph** [comment]
Tokens:
post-validation-valid-fg
post-validation-invalid-fg

Variant 1:
<p class="validation invalid icon">Error</p>

Variant 2:
[type="checkbox"] ~ .validation { // Show icon }

**Resolution**: 
- Variant to be used is inferred by type of component used (variant 2)

**Comment by myrta2302** [comment]
### Tokens

post.validation.error				#B200000
post.validation.success	  			#107800	
post.validation.font-size			14px			
post.validation.text.padding.block.text		6px	
post.validation.text.padding.inline.text	2px	
post.validation.list.gap.inline			8/6/4px
post.validation.list.padding.block.text		1px
post.validation.list.icon.size			24/22/20px
post.validation.list.icon.padding		0/1/2px

**Comment by Vandapanda** [comment]
Added this one to the pattern discussion as its connected to the other issue I got

**Comment by myrta2302** [comment]
Validation Documentation & examples within various Form components need modifications( e.g. missing aria-describedby element, hint before error message etc).

**Comment by oliverschuerch** [comment]
Let's concentrate on the components needed for PPNL:
- Text input
- Select
- Textarea
- Checkbox
- Radio Button
- Card Control (if it does not take to much time)

**Comment by Vandapanda** [comment]
Tokenised and implemented in some examples. [Link for Input](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=6775-79990&m=dev&t=D4qSkf6chebEhOlC-1) [Link for Group](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=416-9087&m=dev&t=D4qSkf6chebEhOlC-1)

**Comment by myrta2302** [comment]
@sandra-post ->Design Review: https://preview-3824--swisspost-design-system-next.netlify.app/
