### ISSUE TITLE
[component]: Local header

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3636]
Create the local header component. This is a new part of the header capable of displaying an application title and holding some optional, additional controls that can be slotted in.

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=2932-40151&t=saHtog1amMMrG60S-4

### Requirements
- Slot for a page title
- Slot for random stuff to the right

### Reference
![image](https://github.com/user-attachments/assets/3921caf4-e960-4e02-9e35-f1d0d16584f7)

```[tasklist]
### Tasks
- [ ] Check design, is everything ready for development
- [ ] Create the `<post-local-header>` component
- [ ] Add documentation
- [ ] Add e2e tests
- [ ] Add visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Component naming possibilities:
- post-local-header
- post-header-local
- post-localheader
- post-header-title
