### ISSUE TITLE
[component]: Header

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3637]
Implement the header component, the one that brings all the other smaller parts together. This component should act as a container for the smaller parts, providing slots for putting things into as many of the smaller header parts are optional.

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=558-7012&t=saHtog1amMMrG60S-1

![image](https://github.com/user-attachments/assets/fa65ec7c-e9be-48f8-8d61-8126f6a9e3a4)

![image](https://github.com/user-attachments/assets/908ae8f1-0cc4-454e-8791-c1040cfd6226)

![image](https://github.com/user-attachments/assets/306395d3-48d5-4294-a7f8-0182bb281316)

### Requirements

- Provides slots for components that make up the header and re-orders them as needed to satisfy the responsive design
- Controls scrolling behaviour of the global header (stickyness)
- Controls language navigation variants between mobile and desktop

### Slots
Required or optional slots can be documented but not necessarily checked by inspecting and listening to slotchanges.

- `post-logo`: required, auto-slotted from the `<post-logo>` component
- `audience-navigation`: optional
- `meta-navigation`: optional
- `post-language-switch`: optional, auto-slotted from the `<post-language-switch>` component
- `post-toggle-button`: required, auto-slotted from the `<post-toggle-button>` component
- `title`: optional
- `default`: optional
- `post-mainnavigation`: required, auto-slotted from the `<post-mainnavigation>` component

### Reference

The current implementation on https://post.ch - especially for the mobile behaviour.

### Component structure proposal

```html
<Host>
  <!-- Global navigation -->
  <div class="bg-yellow global-header">
    <div class="left-part">
      <slot name="post-logo"></slot>
      { if desktop <slot name="audience-navigation"></slot> }
    </div>
    <div class="right-part">
      { if desktop <slot name="meta-navigation"></slot> }
      <slot name="controls"></slot>
      { if desktop <slot name="post-language-switch"></slot> }
      { if tablet|mobile <slot name="post-togglebutton"></slot> } <!-- Hidden on desktop -->
    </div>
  </div>

  <!-- Title header - should have 0 height if empty -->
  <div class="title-header">
    <slot name="title"></slot>
    <slot>Default slot here, aligned to the right!</slot>
  </div>

  <!-- Main navigation (add additional elements as needed for the mobile dropdown) -->
  <div class="nav">
    { if tablet|mobile <slot name="audience-navigation"></slot> }
    <slot name="post-mainnavigation"></slot>
    { if tablet|mobile <slot name="meta-navigation"></slot> }
    { if tablet|mobile <slot name="language-switch"></slot> }
  </div>
</Host>
```

### Implementation example

```html
<post-header>
  <!-- wrapper for scroll events and stuff -->

  <post-logo></post-logo>

  <post-list slot="audience-navigation">
    <h3>Audience navigation</h3>
    <post-list-item><a href="">Privatkunden</a></li></post-list-item>
    <post-list-item><a href="">Geschäftskunden</a></post-list-item>
    <post-list-item><a href="">Behörden</a></post-list-item>
  </post-list>

  <post-list slot="meta-navigation">
    <h3>Meta navigation</h3>
    <post-list-item><a href="">Jobs</a></li></post-list-item>
    <post-list-item><a href="">Über uns</a></post-list-item>
  </post-list>

  <post-list slot="controls">
    <post-list-item><a href="">Suche</a></li></post-list-item>
    <post-list-item><a href="">Login</a></post-list-item>
  </post-llist>

  <post-language-switch variant="list|dropdown">
    <post-language-option href="/de" name="Deutsch" code="de-DE"
      >DE</post-language-option
    >
  </post-language-switch>

  <post-toggle-button target="post-main-navigation">
    <post-toggle-button-open>= Menu</post-toggle-button-open>
    <post-toggle-button-closed>X Menu</post-toggle-button-closed>
  </post-toggle-button>

  <h1 slot="title"><a href="">Page title</a></h1>

  <post-main-navigation slot="main">
    ...
  </post-main-navigation>
</post-header>
```

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/3744
- [ ] https://github.com/swisspost/design-system/issues/3633
- [ ] https://github.com/swisspost/design-system/issues/3626
- [ ] https://github.com/swisspost/design-system/issues/3544
- [ ] Create the `<post-header>` component
- [ ] Add e2e tests
- [ ] Add visual regression tests
- [ ] Design review
```
