### ISSUE TITLE
[component]: Display utilities

### ISSUE THREAD

**Issue by leagrdv** [swisspost/design-system#3643]
### Description

Simple classes to allow users to set the display of any HTML element.

### Design

There is no design for the utilities

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [x] HTML/CSS implementation
- [x] Remove any references to bootstrap
- [x] Documentation in Storybook
- [x] Visual regression tests
- [ ] Design review
```
