### ISSUE TITLE
[utilities]: borders

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3645]
### Description

Border utilities to quickly style the border and border-radius of an element.

### Design

https://getbootstrap.com/docs/5.3/utilities/borders/

### Tokens

- [x] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] HTML/CSS implementation
- [x] Remove bootstrap border utilities
- [x] Documentation in Storybook
- [x] Visual regression tests
```

**Comment by gfellerph** [comment]
Resolution:

- no opacity options
- no color options, default color is sandgray-100
- width: 1px or 2px option
- border-radius: 4px, 8px, rounded (9001px)
- no border-styles
- yes to reset classes
