### ISSUE TITLE
[utilities]: flex

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3646]
### Description

Flexbox utilities to manage the layout, alignment, and sizing of grid columns, navigation, components, and more.

### Design

https://getbootstrap.com/docs/5.3/utilities/flex/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [x] Visual regression tests
- [ ] Design review
- [x] Remove flex utilities from bootstrap
```
