### ISSUE TITLE
[utilities]: float

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3647]
### Description

Responsive float utilities to toggle floats on any element, across any breakpoint.

### Design

https://getbootstrap.com/docs/5.3/utilities/float/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Check in Bitbucket if the classes are used: if not close the ticket
- [x] Remove float utilities coming form bootstrap
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [x] Visual regression tests
- [ ] Design review
```
