### ISSUE TITLE
[utilities]: interactions

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3648]
### Description

Utility classes that change how users interact with contents of a website.

### Design

https://getbootstrap.com/docs/5.3/utilities/interactions/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Check in Bitbucket if the classes are used: if not close the ticket
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
- [ ] Remove interaction utilities coming form bootstrap
```

**Comment by gfellerph** [comment]
Closing as not needed.
