### ISSUE TITLE
[utilities]: object fit

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3649]
### Description

Utilities to modify how the content of a [replaced element](https://developer.mozilla.org/en-US/docs/Web/CSS/Replaced_element), such as an <img> or <video>, should be resized to fit its container.

### Design

https://getbootstrap.com/docs/5.3/utilities/object-fit/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Check in Bitbucket if the classes are used: if not close the ticket
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
- [ ] Remove object fit utilities coming form bootstrap
```
