### ISSUE TITLE
[utilities]: opacity

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3650]
### Description

Utilities to control the opacity of elements.

### Design

https://getbootstrap.com/docs/5.3/utilities/opacity/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Check in Bitbucket if the classes are used: if not close the ticket
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [x] Visual regression tests
- [ ] Design review
- [x] Remove opacity utilities coming from bootstrap
```
