### ISSUE TITLE
[utilities]: overflow

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3651]
### Description

Utilities to quickly configure how content overflows an element.

### Design

https://getbootstrap.com/docs/5.3/utilities/overflow/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Check in Bitbucket if the classes are used: if not close the ticket
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
- [ ] Remove overflow utilities coming form bootstrap
```

**Comment by gfellerph** [comment]
Usage analysis: found moderate usage for `overflow-*` classes (100+ results)
