### ISSUE TITLE
[utilities]: position

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3652]
### Description

Utilities to quickly configure the position of an element.

### Design

https://getbootstrap.com/docs/5.3/utilities/position/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Check in Bitbucket if the classes are used: if not close the ticket
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [x] Visual regression tests
- [ ] Design review
- [x] Remove position utilities coming form bootstrap
```

**Comment by gfellerph** [comment]
Usage analysis: found moderate usage for `position-*` classes (100+ results)
