### ISSUE TITLE
[utilities]: shadows

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3653]
### Description

Utilities to add or remove shadows to elements.

### Design

https://getbootstrap.com/docs/5.3/utilities/shadows/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Check in Bitbucket if the classes are used: if not close the ticket
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
- [ ] Remove shadow utilities coming form bootstrap
```

**Comment by gfellerph** [comment]
Usage analysis: found low usage for `shadow-*` classes (10+ results)

**Comment by gfellerph** [comment]
Move elevation to utility classes and create migration instructions from bootstrap to elevation. @gfellerph

**Comment by alizedebray** [comment]
Add `.elevation-none` to remove an existing shadow.
