### ISSUE TITLE
[utilities ]: text align

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3654]
### Description

Utilities to control alignment, wrapping, weight, and more.

### Design

https://getbootstrap.com/docs/5.3/utilities/text/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Check in Bitbucket if the classes are used: if not close the ticket
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
- [x] Remove text utilities coming form bootstrap
```

**Comment by gfellerph** [comment]
Usage analysis: found heavy usage for `text-*` classes (500+ results) but no usage for responsive variants.

**Comment by gfellerph** [comment]
@gfellerph check usage of the other utility classes in bitbucket
