### ISSUE TITLE
[utilities]: vertical alignment

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3655]
### Description

Utilities to easily change the vertical alignment of inline, inline-block, inline-table, and table cell elements.

### Design

https://getbootstrap.com/docs/5.3/utilities/vertical-align/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Check in Bitbucket if the classes are used: if not close the ticket
- [x] HTML/CSS implementation
- [x] Remove vertical alignment utilities coming form bootstrap
- [x] Documentation in Storybook
- [x] Visual regression tests
- [ ] Design review
```
