### ISSUE TITLE
[utilities]: visibility

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3656]
### Description

Utilities to control the visibility of elements, without modifying their display.

### Design

https://getbootstrap.com/docs/5.3/utilities/visibility/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Usage analysis: found no usage of `visible` and low usage of `invisible` classes.

**Comment by gfellerph** [comment]
Closing as not needed.
