### ISSUE TITLE
[utilities]: z-index

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3657]
### Description

Utilities to quickly change the stack level of an element or component.

### Design

https://getbootstrap.com/docs/5.3/utilities/z-index/

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Check in Bitbucket if the classes are used: if not close the ticket
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
- [ ] Remove z-index utilities coming form bootstrap
```

**Comment by gfellerph** [comment]
Usage analysis not possible (limitation of filtering possibilities).

**Comment by gfellerph** [comment]
Closing as not needed.
