### ISSUE TITLE
[component]: List (documents, links, switches)

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3658]
### Description

This component replaces the  [List Group](https://getbootstrap.com/docs/5.3/components/list-group/#basic-example) from Bootstrap. It should use class names that are similar to Bootstrap’s class names to make migration easier.

The list classes must be flexible enough to be applied to list elements, but also to create [lists of links, buttons, etc. in a div element](https://getbootstrap.com/docs/5.3/components/list-group/#links-and-buttons).

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=21-170

### Tokens

- [x] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] #3437
- [ ] Review Design (All states present? Possible to implement?)
- [x] HTML/CSS implementation
- [x] Documentation in Storybook - List Overview
- [x] Documentation in Storybook - Document List Example
- [x] Documentation in Storybook - Link List Example
- [x] Documentation in Storybook - Switch List Example
- [ ] Unit tests
- [ ] End to end tests
- [x] Visual regression tests
- [x] Design review
```

**Comment by leagrdv** [comment]
@sandra-post Could you have a look at the implementation of this component? :)
