### ISSUE TITLE
[component]: Blockquotes

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3665]
### Description

For quoting blocks of content from another source within your document.

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=4204-33806&t=MIUFMPO2Meg2xFcc-1

### Tokens

- [x] Tokens for this component are ready

### Token proposal
- border-left (width/style/color) (or stroke, according to consistency)
- quote-font-weight (size and color are inherited)
- quote-author (size/weight)
- quote-margin-block (outside margin)
- quote-padding-inline (gap between border and text)
- quote-inline-gap (between text and author)

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [x] Visual regression tests
- [x] Design review // Done 18-Nov-2024 Sandra
```

**Comment by oliverschuerch** [comment]
Still not sure how to handle the `cite` element?

**Comment by myrta2302** [comment]
@rouvenpost Should the border color be white in dark scheme?

**Comment by myrta2302** [comment]
It was decided that the `cite` element will have the exact same styling as the Author. So the italic style is to be reset.

**Comment by myrta2302** [comment]
@sandra-post Design Review: https://preview-3882--swisspost-design-system-next.netlify.app/
