### ISSUE TITLE
[helpers]: list helper classes

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3675]
### Description

Add the following list-helper classes mentioned
```[tasklist]
### Tasks
- [ ] Implement list utility class `list-unstyled`
- [ ] Implement list utility class `list-inline` and `list-inline-item`
- [ ] Implement text utility class `text-truncate`
``` 
See for further information: https://getbootstrap.com/docs/5.3/content/typography/#lists

### Design

none

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Remove class definitions from bootstrap
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
```

**Comment by gfellerph** [comment]
Add token spec for inline gap

**Comment by leagrdv** [comment]
Closing as it has been done on PR #4097
