### ISSUE TITLE
Create a health page in the docs

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3689]
In our icons package, we have a `index.html` file, that can be viewed locally by running `pnpm icons:start`.
This html file is using alpine.js to show information about the weekly downloaded icons (from censhare). The showed information is comming from the generated `report.json` file in the icons package.

It would be nice to have this such an overview page in the documentation, so we can share a link with designers, especially, when there are problems with some of the icons.

```[tasklist]
### Tasks
- [x] Create a "health" overview docs page in storybook and its corresponding `health.stories.ts` file
- [x] Do not use an `id` property in the `meta` object in the above mentioned stories file, but use a `title` like `Health`
- [x] Create an "icons" docs page in storybook and its corresponding stories file, set no `id`, but a `title` in `meta` again with the value of `Health/Icons`
- [x] Import the `report.json` from `node_modules/@swisspost/design-system-icons` and try to build the HTML output as it has been done in the above said `index.html`
- [x] Make the whole `Health` section in the managers navigation invisible (for example by using the `manager.scss` file
- [x] Test if you can access the overview page by navigating to `//localhost:9000/?path=/docs/health--docs`
```
