### ISSUE TITLE
Check if bootstrap helper classes need to be reimplemented after getting rid of bootstrap

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3695]
Bootstrap not only provided a lot of uility clases, but also some helper classes.
We need to check if we need to reimplement them or document the breaking change.

For all bellow helper classes, check if the class is used in some Post projects (using [Bitbucket search](https://gitit.post.ch/plugins/servlet/search?q=%22my-class%22)) and if so create a ticket so that we re-implement them.
```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/4232
- [ ] https://github.com/swisspost/design-system/issues/4231
- [ ] https://github.com/swisspost/design-system/issues/4230
- [ ] https://github.com/swisspost/design-system/issues/4229
- [ ] https://github.com/swisspost/design-system/issues/4236
- [ ] https://github.com/swisspost/design-system/issues/4228
- [ ] https://github.com/swisspost/design-system/issues/4227
- [ ] https://github.com/swisspost/design-system/issues/4226
- [ ] https://github.com/swisspost/design-system/issues/4225
- [ ] https://github.com/swisspost/design-system/issues/4224
- [x] https://github.com/swisspost/design-system/issues/4222
- [ ] https://github.com/swisspost/design-system/issues/4233
- [ ] https://github.com/swisspost/design-system/issues/4221
- [ ] https://github.com/swisspost/design-system/issues/4220
- [x] https://github.com/swisspost/design-system/issues/4219
```

**Comment by gfellerph** [comment]
Create a ticket for each helper class as subtickets here, do research on gitit on how frequent these classes are being used and then we decide if we're going to implement them or not.
