### ISSUE TITLE
[component]: Close button

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3697]
### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=17-163

### Tokens

- [x] Tokens for this component are ready

DEVs proposal
BaseComponent: `Elements/Button`
Token set name: Components/Close

As this is a button

- `post-close-size` (size of the `Icon button special / Close` Figma element)
- `post-close-fg` (create only if it differs from `Elements/Button`)
- `post-close-border-radius`
- `post-close-icon-size` (size of the `closeIcon` Figma element)
- `post-close-hover-fg` (create only if it differs from `Elements/Button`)
- focus styles should be inheritable from `Elements/Button`

### Requirements
- Auto slot convention: The close button is meant to be used in other components, therefore it's handy if the close button adds the slot attribute to itself like `<post-closebutton slot="post-closebutton">`. With this in place, components that need a close button can create a `<slot name="post-closebutton">` and the closebutton will be automatically in the correct place without the user having to specify the slot name.
- Rendering: render a `<button>` element internally
- The close button should not have specific closing functionality built in since it's used in many different contexts and does not know what it's going to close tomorrow
- Shadow DOM: don't use shadow DOM for this component. This enables functionality like closing a native `<dialog><form method=dialog>` combo. If the button would be in the shadow DOM, the cross root barrier would prevent the dialog from closing automatically

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [ ] https://github.com/swisspost/design-system/issues/3492
- [x] Web component implementation
- [x] Documentation in Storybook
- [x] End to end tests
- [x] Visual regression tests
- [ ] Design review
```
