### ISSUE TITLE
[component]: Avatar

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#3698]
### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=17-160

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Closing as duplicate of #3210
