### ISSUE TITLE
Align package.json files

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3745]
Some package.json files are not quite exposing the same fields. Analyse all package.json files in the repo and align them.

```[tasklist]
### Tasks
- [ ] Fields used
- [ ] Order of the fields
- [ ] Provide missing fields
- [ ] Define sensible keywords
- [ ] Add missing scripts, for example `clean` to all packages that have a build output
```
