### ISSUE TITLE
Hosting app store badges

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3763]
The way app store badges are implemented, users would have to download and server the badges themselves. While it's flexible, there's some maintenance work involved and we could end up with different app store badges across projects. With the font hosting service we already have a CDN in place where we could upload additional assets like all available app store badges and use them in the component.

```[tasklist]
### Tasks
- [x] Download the appstore badges from apple and google
- [x] Save the english versions of the *.svg files in the repo (include `version`, `language` and `color-mode` in the folder path, e.g. `public/badges/v1/en/light/apple-store-badge.svg`, keep the naming as implemented in the current compnent story).
- [x] Check with @rouvenpost if we should provide the *.eps files as well.
- [x] Add a *.zip per version, so one can download all badge files per version.
```

**Comment by schaertim** [comment]
There is a open PR on the postfonts repository which needs to be reviewed by @gfellerph before this ticket can be completed.

**Comment by gfellerph** [comment]
Open PR might not be there anymore since the migration. Open a new one with official resources from vendors pages. Supported languages must be German, French, Italian and English. Other languages are optional if it's really easy to add them (max. 10 minutes), otherwise we'll add them on request.
