### ISSUE TITLE
[component]: Change the input hint text wrapper from<div> to <p>

### ISSUE THREAD

**Issue by myrta2302** [swisspost/design-system#3834]
### Description

In the documentation, the input hint text is currently rendered within a `<div>` element: [Input Hint Documentation](https://design-system.post.ch/?path=/docs/2df77c32-5e33-402e-bd2e-54d54271ce19--docs). However, it should use a `<p>` element for better semantics and consistency with the validation message, which also uses a `<p>`.

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=577-14513&t=9BfwPJgQaTSo5u5n-0

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by oliverschuerch** [comment]
Could be affected by #3500
