### ISSUE TITLE
[component]: Form Hint

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3853]
### Description

An assistive text display bellow inputs.

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=577-14513&node-type=frame&t=sgt85CaL95uoH9vN-0

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 💻 Tasks
- [x] Review Design (All states present? Possible to implement?)
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [x] Visual regression tests
- [ ] Design review
```
