### ISSUE TITLE
[component]: Container

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3900]
### Description

A container for the grid.

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=26-51

### Tokens

- [x] Tokens for this component are ready

### Token proposal

- grid-container-max-width
- grid-padding-xl
- grid-padding-lg
- grid-padding-md
- grid-padding-sm
- grid-padding-xs
- grid-gutter-xl
- grid-gutter-lg
- grid-gutter-md
- grid-gutter-sm
- grid-gutter-xs

### Tasks

```[tasklist]
### 💻 Tasks
- [x] HTML/CSS implementation
- [x] Documentation in Storybook
- [x] Visual regression tests
```

**Comment by Vandapanda** [comment]
@alizedebray Added tokens. Please check with the Grid basics if we need everything or if we have dupes

**Comment by alizedebray** [comment]
@Vandapanda 
Could you update the margin tokens by padding tokens please?
