### ISSUE TITLE
[component]: Dropdown / Search

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3907]
### Description

❖ Search is the trigger element of the Dropdown / Search component. It opens a list of search term suggestions based on the user input where the user can select one from. 

---
Migrated from Miro

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=589-15346&t=fx28oG7rQpbWMkdN-4

### Tokens

- [x] Tokens for this component are ready

### Tasks

```[tasklist]
### 🎨 Design
- [x] Design component according to WIKIT
- [x] Update dependencies
- [x] Add & test compo in layout examples
- [x] Designer review
- [x] Documentation: Overview and usage (About, compo overview, compo props, usage, examples)
- [x] Documentation: Technical documentation (Anatomy, accessibility)
- [x] Documentation: Review (content correctness, understandability, gaps)
```

```[tasklist]
### 💻 Development
- [ ] https://github.com/swisspost/design-system/issues/3696
- [ ] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Could be merged with https://github.com/swisspost/design-system-planner/issues/52
