### ISSUE TITLE
[component]: Combobox (Chips)

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3912]
### Description

Based on https://github.com/swisspost/design-system/issues/3911

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=18-15

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 🎨 Design
- [ ] https://github.com/swisspost/design-system/issues/3911
- [ ] Design component according to WIKIT
- [ ] Update dependencies
- [ ] Add & test compo in layout examples
- [ ] Designer review
- [ ] Documentation: Overview and usage (About, compo overview, compo props, usage, examples)
- [ ] Documentation: Technical documentation (Anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```
