### ISSUE TITLE
[foundation]: Motion / Micro animation

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3917]
### Description

Define motions / animations / micro-animations for the design system

#### Component candidates for micro animation
- [ ] Back to top
- [ ] Button
- [ ] (Generally arrow for hover state: List item?)

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=13965-174292&t=Eu4XnTwgpQ3BiWPU-4 
( ↳ as section in page [🔴 Backlog](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=13943-51226) )

### Tokens

- [ ] Tokens for this component are ready

### 🔗 References
- [Ideation / Tryout of "Load more" button](https://postchag.sharepoint.com/:v:/r/sites/cwf/Freigegebene%20Dokumente/General/_Internal/Feedback%20and%20inputs/[Idea_Micro-Animation_Load-button_Claassen-Oli_04-2025.mp4](https://postchag.sharepoint.com/:v:/r/sites/cwf/Freigegebene%20Dokumente/General/_Internal/Feedback%20and%20inputs/Idea_Micro-Animation_Load-button_Claassen-Oli_04-2025.mp4?csf=1&web=1&e=TQie1N)?csf=1&web=1&e=TQie1N) by Oli Claassen

### Tasks

```[tasklist]
### 🎨 Design
- [ ] Design component according to WIKIT
- [ ] Update dependencies
- [ ] Add & test compo in layout examples
- [ ] Designer review
- [ ] Documentation: Overview and usage (About, compo overview, compo props, usage, examples)
- [ ] Documentation: Technical documentation (Anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

```[tasklist]
### 💻 Tasks
- [ ] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```
