### ISSUE TITLE
[concept]: Notification concept

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3925]
### Description

Set up a notification concept where things like trigger, disruptiveness, user action, dismissal, priorities, urgencies, classifications are defined.

Status: First version has been created, might need to be reviewed when notification components are being requested for delivery.

(Migrated from Miro)

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=2016-48537&t=mU8LJQj3tQHeaV5i-4

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### Tasks
- [x] Set up initial notification concept draft
- [ ] Review and update concept
```
