### ISSUE TITLE
[component]: Toast (notifications)

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3928]
### Description

Toasts are notifications that can communicate user or system-triggered messages which are not task- but context-related. The toast notifications should be retrievable (not as toast, but as different indication, e.g. badge) by the user after it has been dismissed.

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=1447-8743&t=mU8LJQj3tQHeaV5i-4

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 🎨 Design
- [x] Design component according to WIKIT
- [ ] Update dependencies
- [x] Add & test compo in layout examples
- [x] Designer review
- [x] Documentation: Overview and usage (About, compo overview, compo props, usage, examples)
- [x] Documentation: Technical documentation (Anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by leagrdv** [comment]
Since toasts and banners were heavily linked in the design system, the toasts have pretty much been implemented already with the existing tokens I could find.
