### ISSUE TITLE
[component]: Notification inline

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3929]
### Description

Inline notifications show up in task flows, to communicate the users the status of an action or system. It can also be used as a persistent element on the page to communicate information which needs higher attention than regular text. 

Nota: Replaces "Infobox" component from DS V1

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=1447-8953&t=mU8LJQj3tQHeaV5i-4

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 🎨 Design
- [x] Design component according to WIKIT
- [ ] Update dependencies
- [x] Add & test compo in layout examples
- [x] Designer review
- [x] Documentation: Overview and usage (About, compo overview, compo props, usage, examples)
- [x] Documentation: Technical documentation (Anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```
