### ISSUE TITLE
[foundation]: Card

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3949]
### Description

A card is a container that contains information and actions related to a single topic. The elements can consist of anything from images to headlines, supporting text, buttons and lists. Cards can have flexible layouts and dimensions based on their contents.

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=18-13

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 🎨 Design
- [x] Design component according to WIKIT
- [x] Update dependencies
- [x] Add & test compo in layout examples
- [x] Designer review
- [ ] Documentation: Overview and usage (About, compo overview, compo props, usage, examples)
- [ ] Documentation: Technical documentation (Anatomy, accessibility)
- [x] Documentation: Review (content correctness, understandability, gaps)
```

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```
