### ISSUE TITLE
[foundations]: Colours

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3955]
### Description

Documentation of core colors and style colors

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=26-48

### Tokens

- [x] Tokens for this component are ready

### Tasks

```[tasklist]
### Tasks
- [ ] Review documentation for Colors / Overview and usage
- [ ] Review documentation for Core colors
- [ ] Adjust documentation for Style colors
- [ ] Add signal colors for dark mode
```
