### ISSUE TITLE
[foundation]: Elevation

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3956]
### Description

Elevation is the distance between an object and the surface behind it along the z-axis. It uses shadows and light for this elevation effect. Elevation helps users to tell the visual hierarchy of elements and to understand which ones are interactive. 

Surfaces at different elevations allow to move in front of and behind each other, reflect object separations and can focus the attention on the highest elevation.

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=31-1555

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### 🎨 Design
- [x] Design component according to WIKIT
- [x] Update dependencies
- [x] Add & test compo in layout examples
- [x] Designer review
- [x] Documentation: Overview and usage (About, compo overview, compo props, usage, examples)
- [x] Documentation: Technical documentation (Anatomy, accessibility)
- [x] Documentation: Review (content correctness, understandability, gaps)
```

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```
