### ISSUE TITLE
[foundation]: Layout

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3957]
### Description

Element structure inside different page types. To provide a consistent user experience over various pages, the page content should be structured in a in a seamless way to direct the users attention to the action he/she wants to take.

Page types:
- Startpage und overview pages
- Content pages
- Landing pages
- Micro sites

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=26-52

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
### Startpage und overview pages
- [x] Documentation: Overview and usage 
- [x] Documentation: Content specs for Desktop (1440, 1024), Tablet (780, 600), Mobile (400)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

```[tasklist]
### Content pages
- [x] Documentation: Overview and usage
- [x] Documentation: Content specs for Desktop (1440, 1024), Tablet (780, 600), Mobile (400)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```
```[tasklist]
### Landing pages
- [ ] Documentation: Overview and usage 
- [ ] Documentation: Content specs for Desktop (1440, 1024), Tablet (780, 600), Mobile (400)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```
```[tasklist]
### Micro sites
- [ ] Documentation: Overview and usage 
- [ ] Documentation: Content specs for Desktop (1440, 1024), Tablet (780, 600), Mobile (400)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```
