### ISSUE TITLE
[component]: List simple - Checks inverted

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3966]
### Description

A non-interactive checks list is a list with a check icon prefix for not only better visual identification of the different list items, but also to have an effect of the item being done. 

Newly added inverted version by @Cian77 

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=488-4511&t=dLDlWukq3ObkuZ1v-4

### Tokens

- [ ] Tokens for this component are ready

### Tasks design

```[tasklist]
### 🎨 Design
- [x] Design component according to WIKIT
- [ ] Update dependencies
- [ ] Add & test compo in layout examples // Not necessary since non-inverted version is already added
- [x] Designer review
- [ ] Documentation: Overview and usage (about, compo overview, compo props, usage, examples) // Not necessary, already done with non-inverted version
- [ ] Documentation: Technical documentation (anatomy, accessibility) // Not necessary, already done with non-inverted version
- [ ] Documentation: Review (content correctness, understandability, gaps) // Not necessary, already done with non-inverted version
```

### Tasks development

```[tasklist]
### 💻 Development
- [ ] https://github.com/swisspost/design-system/issues/3438
- [ ] Review Design (All states present? Possible to implement?)
- [ ] Tokenization
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by alizedebray** [comment]
The "List Simple / Checks Inverted" component is actually the "List Simple / Checks" component with a dark color scheme. This will be handled using design tokens.
