### ISSUE TITLE
[foundation]: Iconography

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#3989]
### Description

Add iconography concept to design documentation in Figma, covering topics like:
- Differences / categories “UI icons” and “service icons” concept
- Icon size concept
- Link to Icon library
- instructions how to implement library in file
- Which sizes to use when

### Design
Figma: 🔴 [Backlog / Foundations / Iconography](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=13979-174631&t=Eu4XnTwgpQ3BiWPU-4) (as section)

### Tasks design

```[tasklist]
### 🎨 Design
- [ ] Documentation: Overview and usage (about, compo overview, compo props, usage, examples)
- [ ] Documentation: Technical documentation (anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```
