### ISSUE TITLE
[component]: update card-control web-component to get rid of form-association

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3996]
The web-component implements the used `input` element in its shadowdom. This causes a lot of work for form-association, event binding, valueAccessor, and more.

Instead of this, we could offer a default slot, where DEVs can add their input field. This means, the input element lives in the lightdom and therefore the whole functionality of the input is given by the browser.

### Tasks
- [ ] Implement slot
- [ ] Remove all form-association logic
- [ ] Create event listeners, so we know what's going on on the input element and we can trigger our functionality depending on it
- [ ] Remove angular specific valueAccessors
- [ ] Update docs
- [ ] Update e2e tests (components, components-angular)

**Comment by gfellerph** [comment]
On hold until design v2 is ready. Decicion needed on how to proceed with HTML/CSS component and refine web component tasks.

**Comment by gfellerph** [comment]
Closing as not planned because we're deprecating the web component. FYI @oliverschuerch.
