### ISSUE TITLE
[component]: File Input

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#4001]
### Description

An input with a `type="file"` attribute.

### Design

No design yet.

### Tokens

- [ ] Tokens for this component are ready

### Tasks design

```[tasklist]
### 🎨 Design
- [ ] Design component according to WIKIT
- [ ] Update dependencies
- [ ] Add & test compo in layout examples
- [ ] Designer review
- [ ] Documentation: Overview and usage (about, compo overview, compo props, usage, examples)
- [ ] Documentation: Technical documentation (anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

### Tasks development

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] Tokenization
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Accessibility tests
- [ ] Visual regression tests
- [ ] Design review
```
