### ISSUE TITLE
[component]: listbox

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#4020]
### Description
A listbox presents a list of options and allows a user to select one of them.

```html
<post-listbox>
  <post-listbox-item>
    <post-icon name="3000"></post-icon>
    Option 1
  </post-listbox-item>
  <post-listbox-item>Option 2</post-listbox-item> 
</post-listbox>
```

### Design
This component does not have a design, it must be configurable via CSS custom properties.

#### Shadow DOM 
This component does not make use of shadow DOM.

#### Styling options
- `--post-listbox-item-gap`: Gap between listbox options
- `--post-listbox-heading-gap`: Gap between heading (if shown) and the listbox

These options have not default definition but the can be set on the host by a user.
To achieve this, the following styling can be used:

```css
:host {
  display: flex;
  gap: var(--post-listbox-gap); /* If this variable is defined (by the user) a gap will be set */
}
```

#### Props
- `title-hidden`: the internal title container gets the class `visually-hidden`

#### Variants
- No title: Title is visually hidden `<post-list title-hidden>`
- Custom gap: `<post-list style="--post-listbox-item-gap: 1rem; --post-listbox-heading-gap: 0.5rem">`

#### Accessibility
https://www.w3.org/WAI/ARIA/apg/patterns/listbox/
- The components need to have the correct aria-attributes, roles and keyboard navigation.
- The list and the title have to be connected via `aria-labelledby`

### Tasks development

```[tasklist]
### 💻 Development
- [x] Web component implementation
- [x] Documentation in Storybook
- [x] End to end tests
- [x] Visual regression tests
- [x] Accessibility tests
```

**Comment by myrta2302** [comment]
LISTBOX IMPLEMENTATION

FOCUS (FOR SINGLE SELECT)
When a single-select listbox receives focus: either first option or last selected
(Keyboard Interaction - https://www.w3.org/WAI/ARIA/apg/patterns/listbox/)

FOCUS (FOR MULTISELECT)
When a multiselect listbox receives focus: either first option or first of selected options in the list (sorted list?)
(Keyboard Interaction - https://www.w3.org/WAI/ARIA/apg/patterns/listbox/)

SELECTION (FOR SINGLE SELECT)
Selection follows focus (Note #3 - https://www.w3.org/WAI/ARIA/apg/patterns/listbox/

SELECTION (FOR MULTI SELECT)
Selection toggle with space (Keyboard Interaction - https://www.w3.org/WAI/ARIA/apg/patterns/listbox/

**Comment by myrta2302** [comment]
Issue: Some times it first loads like this 
```
...<post-listbox-item slot="post-listbox-item" role="option" tabindex="-1" data-hydrated="">Option 9</post-listbox-item>
      <post-listbox-item slot="post-listbox-item" role="option" tabindex="-1" data-hydrated="">Option 10</post-listbox-item>
    </div><div role="listbox" tabindex="0" aria-labelledby="listbox-bce8217b-80cc-4a1b-ab18-f5c5f069a0e0" aria-roledescription="This is an example listbox."></div></post-listbox>
```

**Comment by gfellerph** [comment]
Closed listbox PR in favour of the new select concept (https://github.com/swisspost/design-system-planner/issues/52).
