### ISSUE TITLE
[component]: combobox with listbox popup

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#4023]
### Description

A combobox is an input widget that has an associated popup. The popup enables users to choose a value for the input from a collection.

### Design

No design

### Tokens

- [ ] Tokens for this component are ready

### Tasks development

```[tasklist]
### 💻 Development
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Accessibility tests
```

**Comment by gfellerph** [comment]
This is either a [select ](https://github.com/swisspost/design-system-planner/issues/52) (user must choose a value from the popup) or a [text input](https://github.com/swisspost/design-system-planner/issues/34) with suggestions. Closing in favour of both of these.
