### ISSUE TITLE
Remove topic teaser component

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#4027]
The topic teaser component https://design-system.post.ch/?path=/docs/2ffc7a53-c1aa-4ff5-b1e4-fa638591399c--docs along with it's styles and all references can be removed for v9. This is a major change and should be documented in the changeset and the migration documentation for v9.

```[tasklist]
### Tasks
- [ ] Remove topic teaser styles
- [ ] Remove topic teaser story
- [ ] Remove topic teaser references (if any)
```
