### ISSUE TITLE
Remove the carousel styles

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#4028]
Styles for the carousel can be removed (https://design-system.post.ch/?path=/docs/cb3ba4a2-1265-4a20-b184-b85443146efa--docs). This is a major change.

```[tasklist]
### Tasks
- [x] Remove the carousel styles
- [x] Remove the documentation story
- [ ] Remove references (if any)
```
