### ISSUE TITLE
Remove bg classes

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#4061]
With the palettes, the `.bg-*` classes are not needed anymore and should be removed.

```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/4083
- [ ] https://github.com/swisspost/design-system/issues/4060
- [ ] Remove bg classes from the styles
- [ ] Remove all references internally
- [ ] Update the documentation
```
