### ISSUE TITLE
Refactor the icons search page

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#4063]
The icon set we provide becomes bigger and bigger. Therefore we should update the page:

```[tasklist]
### Tasks
- [x] Add a pagination navigation with max. 100 icons per page (test if it works performant, otherwhise decrease the amount of icons per page).
- [x] Add filter radio buttons for "Post" and "UI" icon sets (never show icons from one set along with icons of the other set)
- [ ] https://github.com/swisspost/design-system/issues/4353
- [ ] https://github.com/swisspost/design-system/issues/4354
```

**Comment by gfellerph** [comment]
Create individual tasks from the list and check each on priority and feasibility.
