### ISSUE TITLE
[component]: Assist

### ISSUE THREAD

**Issue by Vandapanda** [swisspost/design-system#4082]
### Description

Component that add some assistive text to input fields, select fields and more. Extracted from the components itself as they behave different than the components and are reused in multiple components. 

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=1266-5470&t=GrgJbutteha0jCak-1

### Tokens

- [x] Tokens for this component are ready

### Tasks design

```[tasklist]
### 🎨 Design
- [ ] Design component according to WIKIT
- [ ] Update dependencies
- [ ] Add & test compo in layout examples
- [ ] Designer review
- [ ] Documentation: Overview and usage (about, compo overview, compo props, usage, examples)
- [ ] Documentation: Technical documentation (anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

### Tasks development

```[tasklist]
### 💻 Development
- [x] Review Design (All states present? Possible to implement?)
- [x] Tokenization
- [x] HTML/CSS implementation
- [ ] Web component implementation
- [x] Documentation in Storybook
- [ ] Unit tests
- [x] End to end tests
- [x] Visual regression tests
- [ ] Design review
```
