### ISSUE TITLE
[design]: Rail navigation

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#4165]
### Description
Side navbar with top-level navigation of active applications and app launcher. // to verify

### Requirements
Get requirements from Matt Schmocker // TODO

### Additional information
- Input via @rouvenpost 
- Component requirement from TPNG
- Requirements to get from Matt Schmocker

### Design
Figma: [Foundations & Components / 🔴 Backlog / Sidenav incl. Railnav](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations---Components-Next-Level?node-id=14478-26955&t=U4wvG4TRcrrpyZzx-4) (section)

### Tokens

- [ ] Tokens for this component are ready

### Tasks design

```[tasklist]
### 🎨 Design
- [ ] Design component according to WIKIT
- [ ] Update dependencies
- [ ] Add & test compo in layout examples
- [ ] Designer review
- [ ] Documentation: Overview and usage (about, compo overview, compo props, usage, examples)
- [ ] Documentation: Technical documentation (anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

### Tasks development

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] Tokenization
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```
