### ISSUE TITLE
[typography]: New font style "H3 extra large"

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#4184]
### Description

Additional font style "H3 extra large" to be added. Specs see Figma table "Headings exceptions" in page [Typography](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=26-49).

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=26-49

### Tokens

- [ ] Tokens for this component are ready

### Tasks design

```[tasklist]
### 🎨 Design
- [ ] Design component according to WIKIT
- [ ] Update dependencies
- [ ] Add & test compo in layout examples
- [ ] Designer review
- [ ] Documentation: Overview and usage (about, compo overview, compo props, usage, examples)
- [x] Documentation: Technical documentation (anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

### Tasks development

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] Tokenization
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Unit tests
- [ ] End to end tests
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by Cian77** [comment]
Hallo @sandra-post Ich habe alles angepasst und nur der neue Style publiziert. Danke für deine grossartige Unterstützung! Lieber Gruss Christian

**Comment by gfellerph** [comment]
Closing as done
