### ISSUE TITLE
Should we use nanoid everywhere we need random ids?

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#4209]
Nano id is a tiny library (100 Bytes) https://github.com/ai/nanoid and we'd be able to generate all of these ids in a more readable format than UUID which is safe but quite large. Nanoid is, depending on the length of the string, equally safe from collisions: https://zelark.github.io/nano-id-cc/.

```[tasklist]
### Tasks
- [x] Update usage of random id generators inside components to use nanoid with at least 6 chars, prefixed with a static `p` to ensure it does not start with a number
- [x] Do not use nanoid for storybook documentation ids
- [x] Check if there are other usages of the `crypto` API elsewhere in the repo
```

**Comment by alionazherdetska** [comment]
<img width="649" alt="Image" src="https://github.com/user-attachments/assets/05820709-2be1-4901-bc47-49270b99dbd6" />

**Comment by gfellerph** [comment]
Generally yes

**Comment by leagrdv** [comment]
outside of the components package, crypto is used a few times in the documentation packages, twice in the internet-header package and once in the icon package.
