### ISSUE TITLE
Megadropdown open state stlyes are missing

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#4263]
Is:
<img width="567" alt="Image" src="https://github.com/user-attachments/assets/9e12e15e-7884-4968-8555-8bfc1998ad64" />

Should:

<img width="395" alt="Image" src="https://github.com/user-attachments/assets/4da9b1f8-d03d-4dea-97b1-6b01276b6edf" />

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=7833-54088&t=l3gfitxD9YkxIDjy-4

```[tasklist]
### Tasks
- [ ] Underline is missing
- [ ] Bold font style is missing
- [ ] Chevron is not turned upside down
```

**Comment by gfellerph** [comment]
Styles exist, but are not applied.
