### ISSUE TITLE
Improve header documentation

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#4279]
The header docs does not have any controls (args). Add the following args to the header docs.

### Controls

- **Application title**: [boolean and string] Controls the presence and content of the slotted `<h1>` 
- **Meta navigation**: [boolean] Controls the presence of the meta navigation ("About us" and "Jobs")
- **Custom controls**: [boolean] Controls the presence of default slot content (currently "Search" and "Login" links in the local header)

### Slots

- `post-logo`: Should be used together with the `<post-logo>` component (#4276)
- `meta-navigation`: Holds an ul with meta nav links
- `post-togglebutton`: Holds the mobile menu toggler (#4277)
- `post-language-switch`: For the post-language-switch component
- `title`: Application title
- `default`: Custom controls or content, right aligned in the local header
- `post-mainnavigation`: Has a default slot because it's only meant to be used in the `<post-header>`

### Required CSS imports

- header
- list
- button

_Utility classes should not be necessary to style the header (https://github.com/swisspost/design-system/issues/4278)._

```[tasklist]
### Tasks
- [x] Add the necessary controls
- [x] Document the slots
- [x] Add documentation about what files are necessary to import
```
