### ISSUE TITLE
[component]: Interactive Card

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#4322]
### Description

Create styles for an interactive card component.

### Design

https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=18-13&p=f&t=2et9Lo1ZSX8eODOw-0

### Tokens

- [ ] Tokens for this component are ready

### Tasks design

```[tasklist]
### 🎨 Design
- [ ] Design component according to WIKIT
- [ ] Update dependencies
- [ ] Add & test compo in layout examples
- [ ] Designer review
- [ ] Documentation: Overview and usage (about, compo overview, compo props, usage, examples)
- [ ] Documentation: Technical documentation (anatomy, accessibility)
- [ ] Documentation: Review (content correctness, understandability, gaps)
```

### Tasks development

```[tasklist]
### 💻 Development
- [ ] Review Design (All states present? Possible to implement?)
- [ ] Tokenisation
- [ ] HTML/CSS implementation
- [ ] Documentation in Storybook
- [ ] Visual regression tests
- [ ] Design review
```

**Comment by rouvenpost** [comment]
- Responsive behavoiur (mobile Viewports) is missing
- Negative Variants are missing
- Custom Content should be removed

**Comment by gfellerph** [comment]
@alizedebray this needs a design review from development and maybe a refinement of the tokens proposal. It would be good to prioritise this component.

**Comment by schaertim** [comment]
**Token Spec Draft:**
All colors: text, background, section, hover will come from pallets
post-card-border-radius: 16
post-card-border-radius-nested: 8px
post-card-enabled-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.16), 0px 0px 2px 0px rgba(0, 0, 0, 0.16) (same as elevation-2)
post-card-hover-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.16), 0px 0px 2px 0px rgba(0, 0, 0, 0.16) (same as elevation-2)
post-card-body-padding-inline: 16px
post-card-body-padding-block: 16px

**Comment by Vandapanda** [comment]
On hold till we decided how to implement the different palettes

**Comment by Vandapanda** [comment]
Retokenize once the color discussion is donne. Otherwise ready for implementation

**Comment by gfellerph** [comment]
Findings for palette colors so far https://github.com/swisspost/design-system/discussions/4511

**Comment by gfellerph** [comment]
Resolution: palette concept needs more work, go with a temporary solution to add component tokens specific to card foundations.

**Comment by leagrdv** [comment]
As discussed during the pattern discussion, `.card-group` should be removed from v9 documentation.
