### ISSUE TITLE
Story: Spacing

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#541]
Create a story about spacing.

```[tasklist]
### Tasks
- [ ] Add a spacing docs page using the [bootstrap docs](https://getbootstrap.com/docs/5.3/utilities/spacing/) and our old [Post-Sizes Reference Table docs](https://design-system.post.ch/#/post-samples/sizing).
- [ ] Add custom made playground to switch between `margin`, `padding`, `gap`, and set the size.
- [ ] Add deprecation warning.
- [ ] Why use rems
- [ ] Add SCSS import informations.
```

Examples:
https://www.bbc.co.uk/gel/features/spacing-units
https://volkswagen.frontify.com/d/rzB71PwpjXgt/documentation#/basics/spacing
https://spectrum.adobe.com/page/spacing/
https://www.decathlon.design/726f8c765/p/061870-layout/b/91b22f
https://telekom.github.io/scale/?path=/docs/guidelines-spacing--page
