### ISSUE TITLE
Styles: optimize switch styles

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#853]
Implement the updated switch design.

The new design uses a color change on the background instead of a sliding track animation and adds a smaller variant.

Figma: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7777%3A33877&t=zTAKJLbklgpXEsSf-1

```[tasklist]
### Tasks
- [ ] Add the smaller variant
- [ ] Update animation from a sliding track to changing the backgorund color
- [ ] Update thumb size
- [ ] Update the documentation
- [ ] Add snapshot tests
- [ ] Design review
- [ ] Fix color-contrast on disabled state (and remove ignored rule from cypress-axe about it in `switch.cy.ts`)
```

**Comment by gfellerph** [comment]
Closing as obsolete
